/* Preset particle definitions (docs/03). Each is a full definition the user
   can duplicate and tweak. `color` falls back to the theme accent when null. */

export const PRESET_PARTICLES = [
  // Snow / Rain / Wind / Fire embers stay here until the Weather engine (V2-10)
  // takes them over (V2 §6/§8). Everything else gets the §6 overhaul treatment.
  { id: 'snow', name: 'Snow', shape: { kind: 'sprite', value: 'dot' }, color: '#eef3ff', behavior: 'fallDown', effects: [], speed: 0.7, speedVar: 0.4, size: 9, sizeVar: 0.5, maxCount: 80, spawn: { area: 'top' }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0.4 } },
  { id: 'rain', name: 'Rain', shape: { kind: 'sprite', value: 'drop' }, color: 'rgba(160,190,230,0.5)', behavior: 'fallDown', effects: [], speed: 6, speedVar: 0.2, size: 14, sizeVar: 0.3, maxCount: 90, spawn: { area: 'top' }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0 } },
  { id: 'autumnLeaves', name: 'Autumn leaves', shape: { kind: 'sprite', value: 'leaf' }, shapes: [{ kind: 'sprite', value: 'leaf' }, { kind: 'emoji', value: '🍂' }], color: '#c9803a', gradient: ['#e0a23c', '#a8521f'], behavior: 'fallDown', effects: [], speed: 1.26, speedVar: 0.4, size: 15, sizeVar: 0.4, maxCount: 36, spawn: { area: 'top' }, lifetime: 'offscreen', rotation: { spin: 0.4, sway: 0.7 } },
  { id: 'summerLeaves', name: 'Summer leaves', shape: { kind: 'sprite', value: 'leaf' }, shapes: [{ kind: 'sprite', value: 'leaf' }, { kind: 'emoji', value: '🌿' }], color: '#7fae7f', gradient: ['#9acd32', '#2e6b2e'], behavior: 'fallDown', effects: [], speed: 0.98, speedVar: 0.4, size: 14, sizeVar: 0.4, maxCount: 30, spawn: { area: 'top' }, lifetime: 'offscreen', rotation: { spin: 0.35, sway: 0.8 } },
  { id: 'cherryBlossoms', name: 'Cherry blossoms', shape: { kind: 'sprite', value: 'petal' }, shapes: [{ kind: 'sprite', value: 'petal' }, { kind: 'emoji', value: '🌸' }], color: '#f5b8c4', gradient: ['#f7c6d0', '#e98aa8'], behavior: 'fallDown', effects: [], speed: 1.04, speedVar: 0.4, size: 13, sizeVar: 0.4, maxCount: 44, spawn: { area: 'top' }, lifetime: 'offscreen', rotation: { spin: 0.5, sway: 0.8 } },
  { id: 'hearts', name: 'Hearts', shape: { kind: 'sprite', value: 'heart' }, shapes: [{ kind: 'sprite', value: 'heart' }, { kind: 'emoji', value: '❤️' }], color: '#e88aa0', gradient: ['#ff9eb5', '#e04060'], behavior: 'floatUp', effects: [], angle: 0, speed: 0.9, speedVar: 0.4, size: 16, sizeVar: 0.4, maxCount: 14, spawn: { area: 'bottom' }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0.5 } },
  { id: 'starfield', name: 'Stars', shape: { kind: 'sprite', value: 'star' }, color: '#cdbcf5', behavior: 'drift', driftAmp: 0.4, effects: ['twinkle'], twinkle: { period: 0.5, min: 0.2, max: 1.0 }, speed: 0.1, speedVar: 0.5, size: 8, sizeVar: 0.6, maxCount: 70, spawn: { area: 'random' }, lifetime: 24, rotation: { spin: 0, sway: 0 } },
  { id: 'shootingStars', name: 'Shooting stars', shape: { kind: 'sprite', value: 'dot' }, color: 'rgba(255,255,255,0.95)', behavior: 'flow', flowAngle: 135, trail: { len: 100, head: 'rgba(255,255,255,0.95)' }, effects: [], speed: 9, speedVar: 0.3, size: 7, sizeVar: 0.4, maxCount: 2, spawn: { xRange: [0, 1], yRange: [0, 0.3], shape: 'box', spread: 1 }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0 } },
  { id: 'bubbles', name: 'Bubbles', shape: { kind: 'sprite', value: 'bubble' }, color: 'rgba(184,236,217,0.8)', behavior: 'floatUp', effects: ['pop'], popRate: 0.06, speed: 1.13, speedVar: 0.5, size: 15, sizeVar: 0.6, maxCount: 28, spawn: { area: 'bottom' }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0.6 } },
  { id: 'tropicalFish', name: 'Tropical fish', shape: { kind: 'emoji', value: '🐠' }, shapes: [{ kind: 'emoji', value: '🐠' }, { kind: 'emoji', value: '🐡' }, { kind: 'emoji', value: '🐟' }], color: '#5ec8e0', behavior: 'swim', effects: [], speed: 0.5, speedVar: 0.4, size: 22, sizeVar: 0.3, maxCount: 10, spawn: { area: 'random' }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0 } },
  { id: 'fireflies', name: 'Fireflies', shape: { kind: 'sprite', value: 'dot' }, color: '#ffe9a3', hueJitter: 30, behavior: 'drift', effects: ['twinkle'], twinkle: { period: 0.8, min: 0.3, max: 0.9 }, speed: 0.4, speedVar: 0.5, size: 9, sizeVar: 0.4, maxCount: 39, spawn: { area: 'random' }, lifetime: 14, rotation: { spin: 0, sway: 0 } },
  { id: 'techGlyphs', name: 'Binary rain', shape: { kind: 'char', value: '01' }, shapes: [{ kind: 'char', value: '0' }, { kind: 'char', value: '1' }], color: 'rgba(90,220,130,0.8)', behavior: 'fallDown', effects: [], speed: 2, speedVar: 0.5, size: 14, sizeVar: 0.3, maxCount: 60, spawn: { area: 'top' }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0 } },
  { id: 'windStreaks', name: 'Wind streaks', shape: { kind: 'sprite', value: 'streak' }, color: 'rgba(255,255,255,0.35)', behavior: 'flowRight', effects: [], speed: 5, speedVar: 0.4, size: 50, sizeVar: 0.5, maxCount: 10, spawn: { area: 'left' }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0 } },
  { id: 'fireEmbers', name: 'Fire embers', shape: { kind: 'sprite', value: 'dot' }, color: '#f2a35e', behavior: 'floatUp', effects: ['twinkle', 'shrink'], speed: 1.1, speedVar: 0.6, size: 7, sizeVar: 0.5, maxCount: 34, spawn: { area: 'bottom' }, lifetime: 7, rotation: { spin: 0, sway: 0.6 } },
  { id: 'smokeWisps', name: 'Smoke wisps', shape: { kind: 'sprite', value: 'wisp' }, color: 'rgba(200,180,190,0.16)', gradient: ['rgba(210,210,218,0.18)', 'rgba(150,150,162,0.03)'], behavior: 'floatUp', effects: ['grow'], speed: 0.5, speedVar: 0.4, size: 46, sizeVar: 0.5, maxCount: 14, spawn: { area: 'bottom' }, lifetime: 12, rotation: { spin: 0.05, sway: 0.4 } },
  { id: 'dandelionSeeds', name: 'Dandelion seeds', shape: { kind: 'sprite', value: 'dandelion' }, color: 'rgba(255,250,235,0.85)', behavior: 'floatUp', effects: [], speed: 0.6, speedVar: 0.5, size: 16, sizeVar: 0.35, maxCount: 22, spawn: { area: 'bottom' }, lifetime: 'offscreen', rotation: { spin: 0.15, sway: 0.8 } },
  { id: 'comets', name: 'Comets', shape: { kind: 'sprite', value: 'dot' }, color: 'rgba(120,200,255,0.95)', behavior: 'flow', flowAngle: 135, trail: { len: 220, head: 'rgba(255,255,255,0.95)', mid: 'rgba(110,224,255,0.8)' }, effects: [], speed: 5, speedVar: 0.5, size: 14, sizeVar: 0.4, maxCount: 3, spawn: { xRange: [0, 1], yRange: [0, 0.3], shape: 'box', spread: 1 }, lifetime: 'offscreen', rotation: { spin: 0, sway: 0 } }
];

/* Pointer FX presets (docs/03): click burst + drag trail definitions. */
export const PRESET_POINTER_FX = [
  { id: 'starSparkle', name: 'Star sparkle', shape: { kind: 'sprite', value: 'star' }, color: '#e8e0ff', behavior: 'random', effects: ['twinkle', 'shrink'], speed: 1.4, speedVar: 0.5, size: 10, sizeVar: 0.5, maxCount: 120, lifetime: 0.9, rotation: { spin: 0.6, sway: 0 } },
  { id: 'blossomBurst', name: 'Blossom burst', shape: { kind: 'sprite', value: 'petal' }, color: '#f5b8c4', behavior: 'random', effects: ['shrink'], speed: 1.6, speedVar: 0.5, size: 11, sizeVar: 0.4, maxCount: 120, lifetime: 1.1, rotation: { spin: 0.8, sway: 0.4 } },
  { id: 'bubblePop', name: 'Bubble pop', shape: { kind: 'sprite', value: 'bubble' }, color: 'rgba(184,236,217,0.9)', behavior: 'floatUp', effects: ['grow', 'shrink'], speed: 1.2, speedVar: 0.5, size: 10, sizeVar: 0.5, maxCount: 120, lifetime: 0.9, rotation: { spin: 0, sway: 0.4 } },
  { id: 'emberSpark', name: 'Ember spark', shape: { kind: 'sprite', value: 'dot' }, color: '#f2a35e', behavior: 'random', effects: ['twinkle', 'shrink'], speed: 2, speedVar: 0.6, size: 7, sizeVar: 0.5, maxCount: 120, lifetime: 0.8, rotation: { spin: 0, sway: 0 } },
  { id: 'heartPop', name: 'Heart pop', shape: { kind: 'sprite', value: 'heart' }, color: '#e88aa0', behavior: 'floatUp', effects: ['shrink'], speed: 1.3, speedVar: 0.5, size: 11, sizeVar: 0.4, maxCount: 120, lifetime: 1, rotation: { spin: 0.3, sway: 0.3 } },
  { id: 'rippleRing', name: 'Ripple ring', shape: { kind: 'sprite', value: 'ring' }, color: 'rgba(255,255,255,0.5)', behavior: 'drift', effects: ['grow', 'shrink'], speed: 0.1, speedVar: 0, size: 18, sizeVar: 0.2, maxCount: 60, lifetime: 0.7, rotation: { spin: 0, sway: 0 } },
  { id: 'leafFlutter', name: 'Leaf flutter', shape: { kind: 'sprite', value: 'leaf' }, color: '#8fc99b', behavior: 'fallDown', effects: ['shrink'], speed: 1, speedVar: 0.5, size: 11, sizeVar: 0.4, maxCount: 100, lifetime: 1.2, rotation: { spin: 0.9, sway: 0.8 } },
  { id: 'confetti', name: 'Confetti', shape: { kind: 'sprite', value: 'leaf' }, color: '#e0a23c', behavior: 'random', effects: ['shrink'], speed: 2.2, speedVar: 0.6, size: 8, sizeVar: 0.5, maxCount: 120, lifetime: 1, rotation: { spin: 1.2, sway: 0.2 } },
  { id: 'glowRing', name: 'Warm glow ring', shape: { kind: 'sprite', value: 'ring' }, color: 'rgba(242,176,107,0.6)', behavior: 'drift', effects: ['grow', 'shrink'], speed: 0.1, speedVar: 0, size: 20, sizeVar: 0.2, maxCount: 60, lifetime: 0.8, rotation: { spin: 0, sway: 0 } },
  { id: 'shimmer', name: 'Light shimmer', shape: { kind: 'sprite', value: 'dot' }, color: 'rgba(255,245,220,0.8)', behavior: 'floatUp', effects: ['twinkle', 'shrink'], speed: 0.8, speedVar: 0.5, size: 7, sizeVar: 0.5, maxCount: 100, lifetime: 0.8, rotation: { spin: 0, sway: 0.2 } },
  { id: 'sandFlick', name: 'Sand flick', shape: { kind: 'sprite', value: 'dot' }, color: 'rgba(220,190,140,0.8)', behavior: 'random', effects: ['shrink'], speed: 2, speedVar: 0.7, size: 5, sizeVar: 0.6, maxCount: 110, lifetime: 0.7, rotation: { spin: 0, sway: 0 } },
  { id: 'orbitPulse', name: 'Orbit ring pulse', shape: { kind: 'sprite', value: 'ring' }, color: 'rgba(143,183,232,0.6)', behavior: 'drift', effects: ['grow', 'shrink'], speed: 0.1, speedVar: 0, size: 16, sizeVar: 0.3, maxCount: 60, lifetime: 0.9, rotation: { spin: 0, sway: 0 } }
];

export function getParticlePreset(id) { return PRESET_PARTICLES.find(p => p.id === id) || null; }
export function getPointerFxPreset(id) { return PRESET_POINTER_FX.find(p => p.id === id) || null; }
