/* Journal suggestion pools (docs/05): write / draw / pause. Easily extended. */

export const PROMPTS = {
  write: [
    'Write about a moment today you want to remember.',
    'What felt heavy today? Set it down here.',
    'Describe today in exactly ten words.',
    'What made you smile most recently?',
    'Write a letter to yourself one year from now.',
    'What are three small things you’re grateful for?',
    'What did you learn today — about anything, or anyone?',
    'Describe your current mood as weather.',
    'What would you do tomorrow if it were entirely yours?',
    'Write about someone who shaped you.',
    'What’s a worry you can water down with facts?',
    'Describe your perfect quiet morning.',
    'What habit is quietly working for you?',
    'What do you need to forgive yourself for?',
    'Write about a place you felt completely at peace.',
    'What’s something you’re looking forward to?',
    'If your energy was a garden today, what grew?',
    'What conversation stayed with you this week?',
    'Write about a small kindness you saw or did.',
    'What’s one thing you’d tell your younger self?',
    'What does “enough” look like for you right now?',
    'Describe a texture, a smell, and a sound from today.',
    'What boundary would make next week softer?',
    'Write the story of your day as a fairy tale opening.',
    'What are you curious about lately?',
    'Which part of today would you replay?',
    'What’s growing slowly in your life that deserves patience?',
    'Write about your favorite hour of the day.',
    'What did you say no to recently? How did it feel?',
    'List five tiny pleasures within arm’s reach.',
    'What’s a fear that’s gotten smaller over time?',
    'Describe the view from a window you love.',
    'What would rest look like tonight, honestly?',
    'Write about a song that found you at the right time.',
    'What compliment do you wish someone would give you? Give it to yourself.',
    'What’s one assumption you could question this week?',
    'Describe a meal that felt like home.',
    'What part of your routine feels like a ritual?',
    'Where does your mind wander when it’s free?',
    'What seeds did you plant today — literal or otherwise?',
    'Write about the last time you surprised yourself.'
  ],
  draw: [
    'Draw your mood as a plant.',
    'Sketch the last thing you ate.',
    'Draw your day as a tiny map.',
    'Doodle the sky as it looked today.',
    'Draw a creature made of three circles.',
    'Sketch your favorite mug — from memory.',
    'Draw a flower that doesn’t exist.',
    'Illustrate the word “calm”.',
    'Draw your desk as an island.',
    'Sketch a constellation of your week.',
    'Draw a door you’d like to open.',
    'Doodle waves until your hand relaxes.',
    'Draw what energy felt like today.',
    'Sketch a tiny house you’d live in.',
    'Draw your shoes having a conversation.',
    'Illustrate your favorite season in five lines.',
    'Draw a jar holding today’s feelings.',
    'Sketch a path through an imaginary garden.',
    'Draw the moon doing something unusual.',
    'Doodle a pattern of leaves, no two alike.',
    'Draw something you can see right now, in 30 seconds.'
  ],
  pause: [
    'Breathe in for 4, hold for 4, out for 6 — repeat five times.',
    'Two-minute meditation: eyes closed, just notice sounds.',
    'Stretch your arms over your head and yawn on purpose.',
    'Unclench your jaw. Drop your shoulders. Soften your gaze.',
    'Look out the farthest window and find three moving things.',
    'Drink a glass of water slowly, like it’s a ceremony.',
    'Stand up and roll your shoulders ten times each way.',
    'Place a hand on your chest and take three slow breaths.',
    'Step outside (or to a window) for one quiet minute.',
    'Name five things you can see, four you can touch, three you can hear.'
  ]
};
