/* 5e feats. Grappler is from the SRD 5.1 (CC-BY-4.0). The remaining entries are
   concise mechanical summaries of the optional feats from the Player's Handbook,
   provided as a quick rules reference (not the books' full descriptive text).
   `source` names the originating book for attribution. */

export const FEATS = [
  { name: 'Grappler', source: 'SRD 5.1', prereq: 'Strength 13+', desc: 'Advantage on attacks vs. a creature you are grappling. You can use an action to try to pin a grappled creature (both restrained).' },
  { name: 'Alert', source: "Player's Handbook", prereq: '—', desc: '+5 bonus to initiative; you can\'t be surprised while conscious; other creatures don\'t gain advantage on attacks against you from being hidden.' },
  { name: 'Athlete', source: "Player's Handbook", prereq: '—', desc: '+1 STR or DEX; standing from prone costs only 5 ft; climb at full speed; running long/high jump after only 5 ft of movement.' },
  { name: 'Actor', source: "Player's Handbook", prereq: '—', desc: '+1 CHA; advantage on Deception and Performance to pass as someone else; mimic speech or sounds you have heard.' },
  { name: 'Charger', source: "Player's Handbook", prereq: '—', desc: 'After Dashing 10+ ft straight, use a bonus action to make one melee attack (+5 damage) or shove 10 ft.' },
  { name: 'Crossbow Expert', source: "Player's Handbook", prereq: '—', desc: 'Ignore loading on crossbows you are proficient with; no disadvantage in melee; bonus-action hand crossbow shot after a one-handed attack.' },
  { name: 'Defensive Duelist', source: "Player's Handbook", prereq: 'Dexterity 13+', desc: 'When wielding a finesse weapon and hit by a melee attack, use your reaction to add your proficiency bonus to AC against that attack.' },
  { name: 'Dual Wielder', source: "Player's Handbook", prereq: '—', desc: '+1 AC while wielding two melee weapons; two-weapon fighting with non-light weapons; draw or stow two one-handed weapons at once.' },
  { name: 'Dungeon Delver', source: "Player's Handbook", prereq: '—', desc: 'Advantage on Perception/Investigation to detect secret doors; advantage on saves vs. traps and resistance to trap damage; search for traps at normal pace.' },
  { name: 'Durable', source: "Player's Handbook", prereq: '—', desc: '+1 CON; when you roll a Hit Die to regain HP, the minimum you regain is twice your CON modifier (min 2).' },
  { name: 'Elemental Adept', source: "Player's Handbook", prereq: 'cast at least one spell', desc: 'Choose acid, cold, fire, lightning, or thunder: your spells ignore resistance to it, and treat any 1 on a damage die for that type as a 2.' },
  { name: 'Grappler (PHB)', source: "Player's Handbook", prereq: 'Strength 13+', desc: 'Advantage on attacks vs. a creature you grapple; action to pin (both restrained).' },
  { name: 'Great Weapon Master', source: "Player's Handbook", prereq: '—', desc: 'On a crit or kill with a melee weapon, make a bonus-action melee attack; optionally take -5 to hit for +10 damage with heavy weapons.' },
  { name: 'Healer', source: "Player's Handbook", prereq: '—', desc: 'Use a healer\'s kit to stabilize and restore 1 HP; as an action, spend a use to restore 1d6+4 + creature\'s Hit Dice HP (once per rest per creature).' },
  { name: 'Heavily Armored', source: "Player's Handbook", prereq: 'medium armor proficiency', desc: '+1 STR; gain proficiency with heavy armor.' },
  { name: 'Heavy Armor Master', source: "Player's Handbook", prereq: 'heavy armor proficiency', desc: '+1 STR; while wearing heavy armor, reduce nonmagical bludgeoning/piercing/slashing damage by 3.' },
  { name: 'Inspiring Leader', source: "Player's Handbook", prereq: 'Charisma 13+', desc: 'Spend 10 minutes to grant up to 6 creatures temporary HP equal to your level + CHA modifier.' },
  { name: 'Keen Mind', source: "Player's Handbook", prereq: '—', desc: '+1 INT; always know which way is north and hours until sunrise/sunset; recall anything seen or heard in the past month.' },
  { name: 'Lightly Armored', source: "Player's Handbook", prereq: '—', desc: '+1 STR or DEX; gain proficiency with light armor.' },
  { name: 'Linguist', source: "Player's Handbook", prereq: '—', desc: '+1 INT; learn three languages; create written ciphers others can\'t decode without a high INT check.' },
  { name: 'Lucky', source: "Player's Handbook", prereq: '—', desc: '3 luck points per long rest: spend one to roll an extra d20 for an attack, check, or save (yours or against you) and choose which to use.' },
  { name: 'Mage Slayer', source: "Player's Handbook", prereq: '—', desc: 'Reaction attack when a creature within 5 ft casts a spell; advantage on saves vs. spells from adjacent casters; you impose disadvantage on their concentration saves.' },
  { name: 'Magic Initiate', source: "Player's Handbook", prereq: '—', desc: 'Learn two cantrips and one 1st-level spell from a chosen class; cast the spell once per long rest without a slot.' },
  { name: 'Martial Adept', source: "Player's Handbook", prereq: '—', desc: 'Learn two Battle Master maneuvers and gain one d6 superiority die (recharged on a rest).' },
  { name: 'Medium Armor Master', source: "Player's Handbook", prereq: 'medium armor proficiency', desc: 'No disadvantage on Stealth in medium armor; add up to +3 DEX (instead of +2) to AC in medium armor.' },
  { name: 'Mobile', source: "Player's Handbook", prereq: '—', desc: 'Speed +10 ft; difficult terrain doesn\'t cost extra when Dashing; no opportunity attacks from a creature you made a melee attack against this turn.' },
  { name: 'Moderately Armored', source: "Player's Handbook", prereq: 'light armor proficiency', desc: '+1 STR or DEX; gain proficiency with medium armor and shields.' },
  { name: 'Mounted Combatant', source: "Player's Handbook", prereq: '—', desc: 'Advantage on melee attacks vs. unmounted creatures smaller than your mount; redirect attacks aimed at your mount to yourself; your mount takes no damage on successful DEX saves (half on fail).' },
  { name: 'Observant', source: "Player's Handbook", prereq: '—', desc: '+1 INT or WIS; read lips; +5 to passive Perception and passive Investigation.' },
  { name: 'Polearm Master', source: "Player's Handbook", prereq: '—', desc: 'Bonus-action butt-end attack (1d4) with glaive/halberd/quarterstaff/spear; opportunity attack when a creature enters your reach.' },
  { name: 'Resilient', source: "Player's Handbook", prereq: '—', desc: '+1 to one ability score and gain proficiency in saving throws using that ability.' },
  { name: 'Ritual Caster', source: "Player's Handbook", prereq: 'INT or WIS 13+', desc: 'Gain a ritual book with two 1st-level ritual spells from a chosen class; can add more rituals you find.' },
  { name: 'Savage Attacker', source: "Player's Handbook", prereq: '—', desc: 'Once per turn, reroll a melee weapon\'s damage dice and use either total.' },
  { name: 'Sentinel', source: "Player's Handbook", prereq: '—', desc: 'Opportunity attacks reduce a target\'s speed to 0; you can opportunity-attack even if they Disengage; reaction attack when an adjacent creature attacks someone other than you.' },
  { name: 'Sharpshooter', source: "Player's Handbook", prereq: '—', desc: 'No disadvantage at long range; ignore half and three-quarters cover; optionally take -5 to hit for +10 damage with ranged weapons.' },
  { name: 'Shield Master', source: "Player's Handbook", prereq: '—', desc: 'Bonus-action shove with a shield after Attack; add shield AC to DEX saves vs. effects targeting only you; take no damage on a successful save (when you would take half).' },
  { name: 'Skilled', source: "Player's Handbook", prereq: '—', desc: 'Gain proficiency in any combination of three skills or tools.' },
  { name: 'Skulker', source: "Player's Handbook", prereq: 'Dexterity 13+', desc: 'Hide when only lightly obscured; missing with a ranged attack doesn\'t reveal you; no disadvantage on Perception in dim light.' },
  { name: 'Spell Sniper', source: "Player's Handbook", prereq: 'cast at least one spell', desc: 'Double the range of attack-roll spells; ignore half and three-quarters cover; learn one attack cantrip.' },
  { name: 'Tavern Brawler', source: "Player's Handbook", prereq: '—', desc: '+1 STR or CON; proficient with improvised weapons; unarmed strike deals 1d4; bonus-action grapple after hitting with an unarmed strike or improvised weapon.' },
  { name: 'Tough', source: "Player's Handbook", prereq: '—', desc: 'Your HP maximum increases by 2 per level (and +2 per level thereafter).' },
  { name: 'War Caster', source: "Player's Handbook", prereq: 'cast at least one spell', desc: 'Advantage on concentration saves; cast with hands full of weapon/shield; cast a spell as an opportunity attack instead of a weapon strike.' },
  { name: 'Weapon Master', source: "Player's Handbook", prereq: '—', desc: '+1 STR or DEX; gain proficiency with four weapons of your choice.' }
];
