/* 5e SRD lore reference (CC-BY-4.0): the example pantheon (Gods of the
   Multiverse) and the planes of existence. Factual listings — name, alignment,
   suggested cleric domains, holy symbol, and the cosmology. */

/* Deity: { name, alignment, domains, symbol } */
export const DEITIES = [
  { name: 'Bahamut', alignment: 'LG', domains: 'Life, War', symbol: "Dragon's head in profile" },
  { name: 'Tiamat', alignment: 'LE', domains: 'Trickery, War', symbol: 'Dragon head with five claw marks' },
  { name: 'Corellon Larethian', alignment: 'CG', domains: 'Light, War', symbol: 'Quarter moon or starburst (elf god)' },
  { name: 'Moradin', alignment: 'LG', domains: 'Knowledge, War', symbol: 'Hammer and anvil (dwarf god)' },
  { name: 'Garl Glittergold', alignment: 'LG', domains: 'Trickery', symbol: 'Gold nugget (gnome god)' },
  { name: 'Yondalla', alignment: 'LG', domains: 'Life', symbol: 'Cornucopia on a shield (halfling goddess)' },
  { name: 'Gruumsh', alignment: 'CE', domains: 'Tempest, War', symbol: 'Unblinking eye (orc god)' },
  { name: 'Lolth', alignment: 'CE', domains: 'Trickery', symbol: 'Spider (drow goddess)' },
  { name: 'Pelor', alignment: 'NG', domains: 'Life, Light', symbol: 'Sun (sun god)' },
  { name: 'Heironeous', alignment: 'LG', domains: 'War', symbol: 'Lightning bolt' },
  { name: 'Hextor', alignment: 'LE', domains: 'War', symbol: 'Fist gripping six downward arrows' },
  { name: 'Boccob', alignment: 'N', domains: 'Knowledge', symbol: 'Eye in a pentagram (god of magic)' },
  { name: 'Wee Jas', alignment: 'LN', domains: 'Death, Knowledge', symbol: 'Red skull before a fireball' },
  { name: 'Nerull', alignment: 'NE', domains: 'Death', symbol: 'Skull and scythe' },
  { name: 'Vecna', alignment: 'NE', domains: 'Death, Knowledge', symbol: 'Hand with an eye in the palm' },
  { name: 'Kord', alignment: 'CG', domains: 'Tempest, War', symbol: 'Sword crossed with lightning' },
  { name: 'Obad-Hai', alignment: 'N', domains: 'Nature', symbol: 'Oak leaf and acorn' },
  { name: 'Ehlonna', alignment: 'NG', domains: 'Life, Nature', symbol: 'Unicorn horn' },
  { name: 'Olidammara', alignment: 'CN', domains: 'Trickery', symbol: 'Laughing mask' },
  { name: 'St. Cuthbert', alignment: 'LN', domains: 'Knowledge', symbol: 'Crumpled hat or starburst of crossbow bolts' },
  { name: 'Bane', alignment: 'LE', domains: 'War', symbol: 'Upright black hand, thumb and fingers together' },
  { name: 'Mystra', alignment: 'NG', domains: 'Knowledge', symbol: 'Circle of seven stars (goddess of magic)' },
  { name: 'Tymora', alignment: 'CG', domains: 'Trickery', symbol: 'Face-up coin (goddess of luck)' },
  { name: 'Tempus', alignment: 'N', domains: 'War', symbol: 'Upright flaming sword (god of war)' },
  { name: 'Lathander', alignment: 'NG', domains: 'Life, Light', symbol: 'Road traveling into a sunrise' },
  { name: 'Selune', alignment: 'CG', domains: 'Knowledge, Life', symbol: 'Pair of eyes surrounded by stars (moon goddess)' },
  { name: 'Shar', alignment: 'NE', domains: 'Death, Trickery', symbol: 'Black disk encircled with a purple border' },
  { name: 'Kelemvor', alignment: 'LN', domains: 'Death', symbol: 'Upright skeletal arm holding scales (judge of the dead)' },
  { name: 'Silvanus', alignment: 'N', domains: 'Nature', symbol: 'Oak leaf (god of wild nature)' },
  { name: 'Talos', alignment: 'CE', domains: 'Tempest', symbol: 'Three lightning bolts from a point (god of storms)' }
];

/* Plane: { name, category, desc } */
export const PLANES = [
  { name: 'Material Plane', category: 'Material', desc: 'The natural world of most adventures — the nexus where the energies of the other planes collide and blend.' },
  { name: 'Feywild', category: 'Echo (Material)', desc: 'The Plane of Faerie: a vivid, magical reflection of the Material Plane, home to fey such as elves, dryads, and hags.' },
  { name: 'Shadowfell', category: 'Echo (Material)', desc: 'The Plane of Shadow: a dim, desaturated echo of the Material Plane, sapping color and emotion; home to shadar-kai and the undead.' },
  { name: 'Ethereal Plane', category: 'Transitive', desc: 'A misty, fog-bound dimension overlapping the Material and Inner Planes; the Border Ethereal lets travelers move unseen.' },
  { name: 'Astral Plane', category: 'Transitive', desc: 'A silvery void of thought and dream that connects to the Outer Planes; travelers project here via silver cords.' },
  { name: 'Plane of Air', category: 'Inner (Elemental)', desc: 'An endless open sky of soaring winds; home to djinn and air elementals.' },
  { name: 'Plane of Earth', category: 'Inner (Elemental)', desc: 'A realm of solid rock, soil, and gems; home to dao and earth elementals.' },
  { name: 'Plane of Fire', category: 'Inner (Elemental)', desc: 'A blazing expanse of flame and ash; home to efreet and fire elementals.' },
  { name: 'Plane of Water', category: 'Inner (Elemental)', desc: 'A boundless ocean without surface or floor; home to marids and water elementals.' },
  { name: 'Elemental Chaos', category: 'Inner (Elemental)', desc: 'The churning border where the four Elemental Planes meet and war in raw, mixed fury.' },
  { name: 'Positive Plane', category: 'Energy', desc: 'The source of life energy and radiance; so overwhelmingly vital it can burn unprotected visitors away.' },
  { name: 'Negative Plane', category: 'Energy', desc: 'A void of entropy and death that drains life; the source of necrotic energy and undeath.' },
  { name: 'Mount Celestia', category: 'Outer (Upper)', desc: 'Seven Heavens of pure law and good — a mountain of seven ascending terraces of celestial order.' },
  { name: 'Bytopia', category: 'Outer (Upper)', desc: 'The Twin Paradises of cooperative toil; lawful good with a streak of freedom.' },
  { name: 'Elysium', category: 'Outer (Upper)', desc: 'The plane of pure good and contentment; a haven of peace and beauty.' },
  { name: 'The Beastlands', category: 'Outer (Upper)', desc: 'A wild paradise of unspoiled nature, where good and freedom run as one.' },
  { name: 'Arborea', category: 'Outer (Upper)', desc: 'Olympian Glades of passionate good and chaos; home to elf gods and exuberant celestials.' },
  { name: 'Ysgard', category: 'Outer (Upper)', desc: 'Heroic battlefields of chaos and glory; the slain rise to fight again each day.' },
  { name: 'Limbo', category: 'Outer (Neutral)', desc: 'Ever-changing chaos shaped by thought and will; home to the slaadi and githzerai.' },
  { name: 'Pandemonium', category: 'Outer (Lower)', desc: 'Howling, wind-torn caverns of madness; chaotic and cruel.' },
  { name: 'The Abyss', category: 'Outer (Lower)', desc: 'Infinite layers of chaotic evil; the birthplace and battleground of the demons.' },
  { name: 'Carceri', category: 'Outer (Lower)', desc: 'The Tarterian Depths: a prison plane of betrayal, where the exiled and damned are bound.' },
  { name: 'Hades', category: 'Outer (Lower)', desc: 'The Gray Waste: utter neutral evil that drains hope, color, and emotion from all who linger.' },
  { name: 'Gehenna', category: 'Outer (Lower)', desc: 'Volcanic slopes of greed and suspicion; lawful-tinged evil and home to the yugoloths.' },
  { name: 'The Nine Hells of Baator', category: 'Outer (Lower)', desc: 'Nine layers of tyrannical, lawful evil ruled by the archdevils and Asmodeus.' },
  { name: 'Acheron', category: 'Outer (Lower)', desc: 'Iron cubes adrift in endless war; lawful evil dedicated to conquest.' },
  { name: 'Mechanus', category: 'Outer (Neutral)', desc: 'A realm of clockwork gears and absolute order; home to the modrons and Primus.' },
  { name: 'Arcadia', category: 'Outer (Upper)', desc: 'Fields of peaceful, perfect order; lawful good shading toward strict control.' },
  { name: 'The Outlands & Sigil', category: 'Outer (Neutral)', desc: 'The plane of true neutrality, with the ring-shaped City of Doors (Sigil) at its infinite center — a hub to everywhere.' },
  { name: 'The Far Realm', category: 'Beyond', desc: 'An alien dimension outside the known cosmology; contact warps minds and bodies. Source of aberrations.' }
];
