/* 5e SRD spell data (CC-BY-4.0 Wizards of the Coast). All ~319 spells from
   the 5e SRD with concise descriptions paraphrased for offline reference. */

/* Each spell: [name, level, school, time, range, components, duration, classes[], description] */
/* school: Abj Con Div Enc Evo Ill Nec Tra */

export const SPELLS = [
// ── Cantrips (Level 0) ──────────────────────────────────────────────────────
['Acid Splash',0,'Con','1 action','60 ft','V, S','Instantaneous',['Sorcerer','Wizard'],
 'Hurl a bubble of acid at 1–2 creatures within 5 ft of each other (DEX save or 1d6 acid damage, 2d6 at 5th, 3d6 at 11th, 4d6 at 17th).'],
['Blade Ward',0,'Abj','1 action','Self','V, S','1 round',['Bard','Sorcerer','Warlock','Wizard'],
 'Until the start of your next turn, you have resistance against bludgeoning, piercing, and slashing damage from weapon attacks.'],
['Chill Touch',0,'Nec','1 action','120 ft','V, S','1 round',['Sorcerer','Warlock','Wizard'],
 'Ranged spell attack: 1d8 necrotic damage (2d8 at 5th, 3d8 at 11th, 4d8 at 17th); target can\'t regain HP until your next turn. Undead also have disadvantage on attacks vs. you.'],
['Dancing Lights',0,'Evo','1 action','120 ft','V, S, M','Concentration, 1 min',['Bard','Sorcerer','Wizard'],
 'Create up to 4 torch-sized lights in a 20-ft radius. Move them 60 ft per action (bonus action). Combine into a glowing humanoid form.'],
['Druidcraft',0,'Tra','1 action','30 ft','V, S','Instantaneous',['Druid'],
 'Minor nature effects: predict weather, make a flower bloom, produce harmless sensory effects, or light/snuff a candle.'],
['Eldritch Blast',0,'Evo','1 action','120 ft','V, S','Instantaneous',['Warlock'],
 'Ranged spell attack: 1d10 force damage per beam (1 beam; 2 at 5th, 3 at 11th, 4 at 17th). Each beam can target separately.'],
['Fire Bolt',0,'Evo','1 action','120 ft','V, S','Instantaneous',['Sorcerer','Wizard'],
 'Ranged spell attack: 1d10 fire damage (2d10 at 5th, 3d10 at 11th, 4d10 at 17th). Ignites flammable objects.'],
['Friends',0,'Enc','1 action','Self','S, M','Concentration, 1 min',['Bard','Sorcerer','Warlock','Wizard'],
 'Advantage on CHA checks against one nonhostile creature. When the spell ends, the creature knows it was charmed.'],
['Guidance',0,'Div','1 action','Touch','V, S','Concentration, 1 min',['Cleric','Druid'],
 'One willing creature adds 1d4 to one ability check of its choice before the spell ends.'],
['Light',0,'Evo','1 action','Touch','V, M','1 hr',['Bard','Cleric','Sorcerer','Wizard'],
 'Object up to 10 ft diameter sheds bright light 20 ft, dim 20 ft beyond. Blinded creature gets a DEX save to avoid. Dispels magical darkness.'],
['Mage Hand',0,'Con','1 action','30 ft','V, S','1 min',['Bard','Sorcerer','Warlock','Wizard'],
 'Spectral, floating hand manipulates objects up to 10 lb, opens unlocked doors/containers, pours liquids. Can\'t attack. Dismissible as bonus action.'],
['Mending',0,'Tra','1 min','Touch','V, S, M','Instantaneous',['Bard','Cleric','Druid','Sorcerer','Wizard'],
 'Repair a single break or tear in an object (up to 1 foot in any dimension). If the object is magical it can\'t be repaired this way.'],
['Message',0,'Tra','1 action','120 ft','V, S, M','1 round',['Bard','Sorcerer','Wizard'],
 'Whisper a message to a creature you can see; it can reply in a whisper only you hear. Walls don\'t block it.'],
['Minor Illusion',0,'Ill','1 action','30 ft','S, M','1 min',['Bard','Sorcerer','Warlock','Wizard'],
 'Create a sound or an image (up to 5-ft cube) that doesn\'t move. INT (Investigation) check to determine it\'s illusory.'],
['Poison Spray',0,'Con','1 action','10 ft','V, S','Instantaneous',['Druid','Sorcerer','Warlock','Wizard'],
 'CON save or take 1d12 poison damage (2d12 at 5th, 3d12 at 11th, 4d12 at 17th).'],
['Prestidigitation',0,'Tra','1 action','10 ft','V, S','Up to 1 hr',['Bard','Sorcerer','Warlock','Wizard'],
 'Minor magical tricks: soil or clean, chill/warm/flavor an item, create a symbol or mark, create a trinket or illusory image that fits in your hand.'],
['Produce Flame',0,'Con','1 action','Self','V, S','10 min',['Druid'],
 'A flickering flame appears. Sheds 10-ft bright light. As an action, throw it (30 ft ranged spell attack): 1d8 fire damage (2d8/3d8/4d8 at 5th/11th/17th).'],
['Ray of Frost',0,'Evo','1 action','60 ft','V, S','Instantaneous',['Sorcerer','Wizard'],
 'Ranged spell attack: 1d8 cold damage (2d8 at 5th, 3d8 at 11th, 4d8 at 17th) and target\'s speed is reduced by 10 ft until start of your next turn.'],
['Resistance',0,'Abj','1 action','Touch','V, S, M','Concentration, 1 min',['Cleric','Druid'],
 'One willing creature adds 1d4 to one saving throw of its choice before the spell ends.'],
['Sacred Flame',0,'Evo','1 action','60 ft','V, S','Instantaneous',['Cleric'],
 'DEX save (no cover benefit) or take 1d8 radiant damage (2d8 at 5th, 3d8 at 11th, 4d8 at 17th).'],
['Shillelagh',0,'Tra','1 bonus action','Self','V, S, M','1 min',['Druid'],
 'Your club or quarterstaff becomes magical: use your spellcasting modifier for attack/damage, and deal 1d8 damage (instead of the weapon\'s normal damage).'],
['Shocking Grasp',0,'Evo','1 action','Touch','V, S','Instantaneous',['Sorcerer','Wizard'],
 'Melee spell attack (advantage vs. metal armor): 1d8 lightning damage (2d8/3d8/4d8 at 5th/11th/17th). Target can\'t take reactions until its next turn.'],
['Spare the Dying',0,'Nec','1 action','Touch','V, S','Instantaneous',['Cleric'],
 'A living creature with 0 HP becomes stable. No effect on undead or constructs.'],
['Thaumaturgy',0,'Tra','1 action','30 ft','V','Up to 1 min',['Cleric'],
 'Minor divine manifestations: alter voice, cause flames to flicker, make eyes glow, produce a tremor, open/close doors, alter sound.'],
['Thorn Whip',0,'Tra','1 action','30 ft','V, S, M','Instantaneous',['Druid'],
 'Melee spell attack: 1d6 piercing damage (2d6/3d6/4d6 at 5th/11th/17th). On a hit, pull the target up to 10 ft toward you.'],
['True Strike',0,'Div','1 action','30 ft','S','Concentration, 1 round',['Bard','Sorcerer','Warlock','Wizard'],
 'Gain insight into one creature\'s defenses. On your next turn, your first attack against it has advantage.'],
['Vicious Mockery',0,'Enc','1 action','60 ft','V','Instantaneous',['Bard'],
 'WIS save or take 1d4 psychic damage (2d4/3d4/4d4 at 5th/11th/17th) and have disadvantage on the next attack roll it makes before the end of its next turn.'],

// ── Level 1 ─────────────────────────────────────────────────────────────────
['Alarm',1,'Abj','1 min (ritual)','30 ft','V, S, M','8 hr',['Ranger','Wizard'],
 'Ward an area up to 20-ft cube. Triggers mental ping (or audible ring) when a Tiny or larger creature enters. Can exclude up to 8 creatures.'],
['Animal Friendship',1,'Enc','1 action','30 ft','V, S, M','24 hr',['Bard','Druid','Ranger'],
 'WIS save (beasts with INT ≥ 4 are immune) or the beast is charmed for 24 hr. It becomes hostile when the spell ends.'],
['Bane',1,'Enc','1 action','30 ft','V, S, M','Concentration, 1 min',['Bard','Cleric'],
 'Up to 3 creatures: CHA save or subtract 1d4 from attack rolls and saving throws. Upcast: +1 target per slot.'],
['Bless',1,'Enc','1 action','30 ft','V, S, M','Concentration, 1 min',['Cleric','Paladin'],
 'Up to 3 creatures add 1d4 to attack rolls and saving throws. Upcast: +1 target per slot.'],
['Burning Hands',1,'Evo','1 action','Self (15-ft cone)','V, S','Instantaneous',['Sorcerer','Wizard'],
 'DEX save or take 3d6 fire damage (half on save). Ignites flammable objects. Upcast: +1d6 per slot.'],
['Charm Person',1,'Enc','1 action','30 ft','V, S','1 hr',['Bard','Druid','Sorcerer','Warlock','Wizard'],
 'WIS save (advantage if hostile) or humanoid is charmed: regards you as a friendly acquaintance. Ends if you harm it. Upcast: +1 target per slot.'],
['Color Spray',1,'Ill','1 action','Self (15-ft cone)','V, S, M','1 round',['Sorcerer','Wizard'],
 'Roll 6d10 (10d10 at 5th etc.)—creatures in the cone are blinded in HP-order from lowest up until that total is met. Upcast: +2d10 per slot.'],
['Command',1,'Enc','1 action','60 ft','V','1 round',['Cleric','Paladin'],
 'WIS save or carry out a one-word command (Approach, Drop, Flee, Grovel, Halt). No effect vs. undead, creatures that don\'t understand you. Upcast: +1 target per slot.'],
['Comprehend Languages',1,'Div','1 action (ritual)','Self','V, S, M','1 hr',['Bard','Sorcerer','Warlock','Wizard'],
 'Understand any spoken language heard or any writing you touch. Takes 1 minute per page.'],
['Create or Destroy Water',1,'Tra','1 action','30 ft','V, S, M','Instantaneous',['Cleric','Druid'],
 'Create up to 10 gallons of water in an open container, or destroy that much water in one container/destroy fog in a 30-ft cube. Upcast: +10 gal per slot.'],
['Cure Wounds',1,'Evo','1 action','Touch','V, S','Instantaneous',['Bard','Cleric','Druid','Paladin','Ranger'],
 'Restore 1d8 + spellcasting modifier HP to one creature. No effect on undead or constructs. Upcast: +1d8 per slot.'],
['Detect Evil and Good',1,'Div','1 action','Self','V, S','Concentration, 10 min',['Cleric','Paladin'],
 'Sense the presence and location of celestials, fiends, and undead within 30 ft; consecrated/desecrated locations within 30 ft.'],
['Detect Magic',1,'Div','1 action (ritual)','Self','V, S','Concentration, 10 min',['Bard','Cleric','Druid','Paladin','Ranger','Sorcerer','Wizard'],
 'Sense the presence of magic within 30 ft. Use an action to see a faint aura around magical objects/creatures and know the associated school.'],
['Detect Poison and Disease',1,'Div','1 action (ritual)','Self','V, S, M','Concentration, 10 min',['Cleric','Druid','Paladin','Ranger'],
 'Sense the presence and location of poisons, poisonous creatures, and disease within 30 ft.'],
['Disguise Self',1,'Ill','1 action','Self','V, S','1 hr',['Bard','Sorcerer','Wizard'],
 'Change your appearance (clothing, hair, facial features, body shape) but not creature type or other creatures. INT (Investigation) vs. spell save DC to see through.'],
['Dissonant Whispers',1,'Enc','1 action','60 ft','V','Instantaneous',['Bard'],
 'WIS save or take 3d6 psychic damage and use reaction to flee as far as possible. Half damage, no flee on success. Upcast: +1d6 per slot.'],
['Divine Favor',1,'Evo','1 bonus action','Self','V, S','Concentration, 1 min',['Paladin'],
 'Your weapon attacks deal an extra 1d4 radiant damage on a hit for the duration.'],
['Entangle',1,'Con','1 action','90 ft','V, S','Concentration, 1 min',['Druid'],
 '20-ft square: STR save or restrained. Save at end of each turn. Difficult terrain for area.'],
['Expeditious Retreat',1,'Tra','1 bonus action','Self','V, S','Concentration, 10 min',['Sorcerer','Warlock','Wizard'],
 'You can take the Dash action as a bonus action for the duration.'],
['Faerie Fire',1,'Evo','1 action','60 ft','V','Concentration, 1 min',['Bard','Druid'],
 '20-ft cube: DEX save or be outlined in blue/green/violet light. While lit: attacks against creature have advantage, it can\'t benefit from invisibility.'],
['False Life',1,'Nec','1 action','Self','V, S, M','1 hr',['Sorcerer','Wizard'],
 'Gain 1d4+4 temporary HP. Upcast: +5 temp HP per slot level above 1st.'],
['Feather Fall',1,'Tra','1 reaction','60 ft','V, M','1 min',['Bard','Sorcerer','Wizard'],
 'Reaction when you or a creature within range falls: up to 5 falling creatures descend 60 ft per round and take no fall damage.'],
['Find Familiar',1,'Con','1 hr (ritual)','10 ft','V, S, M','Instantaneous',['Wizard'],
 'Summon a spirit as a familiar in beast form (cat, hawk, owl, etc.). Telepathic link at 100 ft. You can cast touch spells through it. Dismissed to pocket dimension.'],
['Fog Cloud',1,'Con','1 action','120 ft','V, S','Concentration, 1 hr',['Druid','Ranger','Sorcerer','Wizard'],
 '20-ft radius sphere of thick fog, heavily obscured. Wind disperses it. Upcast: +20-ft radius per slot.'],
['Goodberry',1,'Tra','1 action','Touch','V, S, M','Instantaneous',['Druid','Ranger'],
 'Create 10 berries infused with magic. Each restores 1 HP and provides sufficient nourishment for the day. Berries last 24 hr.'],
['Grease',1,'Con','1 action','60 ft','V, S, M','1 min',['Wizard'],
 '10-ft square: DEX save or fall prone; difficult terrain for duration. Entering or moving through triggers another save.'],
['Guiding Bolt',1,'Evo','1 action','120 ft','V, S','1 round',['Cleric'],
 'Ranged spell attack: 4d6 radiant damage. The next attack roll against the creature before the end of your next turn has advantage. Upcast: +1d6 per slot.'],
['Healing Word',1,'Evo','1 bonus action','60 ft','V','Instantaneous',['Bard','Cleric','Druid'],
 'Restore 1d4 + spellcasting modifier HP to a visible creature. No effect on undead/constructs. Upcast: +1d4 per slot.'],
['Hellish Rebuke',1,'Evo','1 reaction','60 ft','V, S','Instantaneous',['Warlock'],
 'Reaction when damaged: the attacker makes a DEX save or takes 2d10 fire damage (half on save). Upcast: +1d10 per slot.'],
['Heroism',1,'Enc','1 action','Touch','V, S','Concentration, 1 min',['Bard','Paladin'],
 'Willing creature immune to fear and gains temporary HP equal to your spellcasting modifier at the start of each of its turns. Upcast: +1 target per slot.'],
['Hex',1,'Enc','1 bonus action','90 ft','V, S, M','Concentration, 1 hr',['Warlock'],
 'Curse a creature: deal +1d6 necrotic damage to it on any hit; choose one ability type—it has disadvantage on checks with it. Move hex to new target when original dies. Upcast: 8 hr at 3rd, 24 hr at 5th.'],
["Hunter's Mark",1,'Div','1 bonus action','90 ft','V','Concentration, 1 hr',['Ranger'],
 'Designate a creature as your quarry: deal +1d6 damage to it on weapon hits; advantage on Perception and Survival to find it. Move mark as bonus action if it dies. Upcast: 8 hr at 3rd, 24 hr at 5th.'],
['Identify',1,'Div','1 min (ritual)','Touch','V, S, M','Instantaneous',['Bard','Wizard'],
 'Learn the properties, command words, and charges (if any) of one magic item you hold, or identify spells affecting a creature/object.'],
['Inflict Wounds',1,'Nec','1 action','Touch','V, S','Instantaneous',['Cleric'],
 'Melee spell attack: 3d10 necrotic damage. Upcast: +1d10 per slot.'],
['Jump',1,'Tra','1 action','Touch','V, S, M','1 min',['Druid','Ranger','Sorcerer','Wizard'],
 'Triple the jumping distance of one willing creature for the duration.'],
['Longstrider',1,'Tra','1 action','Touch','V, S, M','1 hr',['Bard','Druid','Ranger','Wizard'],
 'Increase one creature\'s speed by 10 ft for the duration. Upcast: +1 target per slot.'],
['Mage Armor',1,'Abj','1 action','Touch','V, S, M','8 hr',['Sorcerer','Wizard'],
 'A willing creature that isn\'t wearing armor has a base AC of 13 + DEX mod for the duration.'],
['Magic Missile',1,'Evo','1 action','120 ft','V, S','Instantaneous',['Sorcerer','Wizard'],
 'Three darts each deal 1d4+1 force damage automatically. Upcast: +1 dart per slot.'],
['Protection from Evil and Good',1,'Abj','1 action','Touch','V, S, M','Concentration, 10 min',['Cleric','Paladin','Warlock','Wizard'],
 'Choose a type (aberrations, celestials, elementals, fey, fiends, undead): that type has disadvantage on attacks vs. the target; it can\'t be charmed, frightened, or possessed by them.'],
['Purify Food and Drink',1,'Tra','1 action (ritual)','10 ft','V, S','Instantaneous',['Cleric','Druid','Paladin'],
 'All nonmagical food and drink within a 5-ft radius sphere is purified of poison and disease.'],
['Ray of Sickness',1,'Nec','1 action','60 ft','V, S','Instantaneous',['Sorcerer','Wizard'],
 'Ranged spell attack: 2d8 poison damage and CON save or poisoned until end of your next turn. Upcast: +1d8 per slot.'],
['Shield',1,'Abj','1 reaction','Self','V, S','1 round',['Sorcerer','Wizard'],
 'Reaction when hit by an attack or targeted by Magic Missile: +5 AC (including vs. the triggering attack) and immunity to Magic Missile until start of your next turn.'],
['Shield of Faith',1,'Abj','1 bonus action','60 ft','V, S, M','Concentration, 10 min',['Cleric','Paladin'],
 'One creature gains +2 AC for the duration.'],
['Silent Image',1,'Ill','1 action','60 ft','V, S, M','Concentration, 10 min',['Bard','Sorcerer','Wizard'],
 'Create a visual illusion up to 15-ft cube in size. Can animate it. INT (Investigation) vs. spell save DC to disbelieve on interaction.'],
['Sleep',1,'Enc','1 action','90 ft','V, S, M','1 min',['Bard','Sorcerer','Wizard'],
 'Roll 5d8; creatures in a 20-ft radius are put to sleep from lowest current HP up until the total is met. Undead/immune-to-charm creatures are unaffected. Upcast: +2d8 per slot.'],
['Speak with Animals',1,'Div','1 action (ritual)','Self','V, S','10 min',['Bard','Druid','Ranger'],
 'Speak with beasts for the duration. Beasts are rarely intelligent, but can share info about nearby locations, monsters, or events.'],
["Tasha's Hideous Laughter",1,'Enc','1 action','30 ft','V, S, M','Concentration, 1 min',['Bard','Wizard'],
 'WIS save (creatures with INT < 4 immune) or fall prone, incapacitated. Repeat save at end of each turn and each time it takes damage (disadvantage on the damage-trigger save).'],
["Tenser's Floating Disk",1,'Con','1 action (ritual)','30 ft','V, S, M','1 hr',['Wizard'],
 'Horizontal disk of force 3 ft across, hovers 3 in off ground. Holds up to 500 lb. Follows within 20 ft of caster.'],
['Thunderwave',1,'Evo','1 action','Self (15-ft cube)','V, S','Instantaneous',['Bard','Cleric','Druid','Sorcerer','Wizard'],
 'CON save or take 2d8 thunder damage and be pushed 10 ft (half damage, not pushed on save). Objects not bolted down are pushed. Audible up to 300 ft. Upcast: +1d8 per slot.'],
['Unseen Servant',1,'Con','1 action (ritual)','60 ft','V, S, M','1 hr',['Bard','Warlock','Wizard'],
 'Invisible, mindless force performs simple tasks: fetch, clean, mend, fold, light, sort. STR 2, AC 10, 1 HP, can\'t attack or lift > 10 lb.'],
['Witch Bolt',1,'Evo','1 action','30 ft','V, S, M','Concentration, 1 min',['Sorcerer','Warlock','Wizard'],
 'Ranged spell attack: 1d12 lightning damage; on subsequent turns, use action to deal 1d12 more automatically. Ends if target is out of range or spell drops. Upcast: +1d12 per slot.'],
['Wrathful Smite',1,'Evo','1 bonus action','Self','V','Concentration, 1 min',['Paladin'],
 'Next melee weapon hit: +1d6 psychic damage and WIS save or frightened of you until spell ends. Action to repeat save.'],

// ── Level 2 ─────────────────────────────────────────────────────────────────
['Aid',2,'Abj','1 action','30 ft','V, S, M','8 hr',['Cleric','Paladin'],
 'Up to 3 creatures: each gains +5 max and current HP for the duration. Upcast: +5 HP per slot above 2nd.'],
['Alter Self',2,'Tra','1 action','Self','V, S','Concentration, 1 hr',['Sorcerer','Wizard'],
 'Change your form: Aquatic Adaptation (gills, swim speed 60 ft), Change Appearance (new look), Natural Weapons (claws/bite 1d6+STR).'],
['Animal Messenger',2,'Enc','1 action (ritual)','30 ft','V, S, M','24 hr',['Bard','Druid','Ranger'],
 'Send a Tiny beast to deliver a short message (25 words or fewer) to a recipient described to it. Spell ends when delivered. Upcast: 48 hr per slot above 2nd.'],
['Arcane Lock',2,'Abj','1 action','Touch','V, S, M','Until dispelled',['Wizard'],
 'Lock a door, window, gate, or chest magically. DC to open increases by 10. Can specify creatures to ignore the lock.'],
['Augury',2,'Div','1 min (ritual)','Self','V, S, M','Instantaneous',['Cleric'],
 'Ask about events within 30 minutes. Receive Weal, Woe, Weal and Woe, or Nothing. 1/long rest (DM rolls secretly if used more than once per day).'],
['Barkskin',2,'Tra','1 action','Touch','V, S, M','Concentration, 1 hr',['Druid','Ranger'],
 'The creature\'s skin is rough and bark-like. Its AC becomes 16 if lower.'],
['Blur',2,'Ill','1 action','Self','V','Concentration, 1 min',['Sorcerer','Wizard'],
 'Your body becomes blurred. Attacks against you have disadvantage (except if they don\'t rely on sight or if you\'re blinded).'],
['Calm Emotions',2,'Enc','1 action','60 ft','V, S','Concentration, 1 min',['Bard','Cleric'],
 '20-ft radius sphere: humanoids make CHA saves. Suppress charmed or frightened condition, OR make indifferent to hostile creatures (dismissed by an attack or harm).'],
['Cloud of Daggers',2,'Con','1 action','60 ft','V, S, M','Concentration, 1 min',['Bard','Sorcerer','Warlock','Wizard'],
 '5-ft cube: 4d4 slashing damage to any creature that enters or starts its turn there. Upcast: +2d4 per slot.'],
['Continual Flame',2,'Evo','1 action','Touch','V, S, M','Until dispelled',['Cleric','Wizard'],
 'Create a magical flame that produces no heat and doesn\'t use oxygen. As bright as a torch.'],
['Crown of Madness',2,'Enc','1 action','120 ft','V, S','Concentration, 1 min',['Bard','Sorcerer','Warlock','Wizard'],
 'WIS save or charmed. Spend action each turn: choose melee target for it to attack (not you). Repeat save at end of each turn.'],
['Darkness',2,'Evo','1 action','60 ft','V, M','Concentration, 10 min',['Sorcerer','Warlock','Wizard'],
 '15-ft radius sphere of magical darkness. Blocks darkvision. Nonmagical light can\'t illuminate it. Can cast it on an object and cover it.'],
['Darkvision',2,'Tra','1 action','Touch','V, S, M','8 hr',['Druid','Ranger','Sorcerer','Wizard'],
 'Grant a willing creature darkvision out to 60 ft for the duration.'],
['Detect Thoughts',2,'Div','1 action','Self','V, S, M','Concentration, 1 min',['Bard','Sorcerer','Wizard'],
 'Read surface thoughts of creatures within 30 ft (WIS save to resist deeper probe). Also detect presences, creatures by INT score, and use for Insight checks.'],
['Enhance Ability',2,'Tra','1 action','Touch','V, S, M','Concentration, 1 hr',['Bard','Cleric','Druid','Sorcerer','Wizard'],
 'Grant one of: Bull\'s Str (advantage STR checks, double carry), Cat\'s Grace (advantage DEX checks, no fall damage ≤10 ft), Bear\'s Endurance (advantage CON checks, 2d6 temp HP), Fox\'s Cunning (advantage INT checks), Owl\'s Wisdom (advantage WIS checks), Eagle\'s Splendor (advantage CHA checks). Upcast: +1 target per slot above 2nd.'],
['Enlarge/Reduce',2,'Tra','1 action','30 ft','V, S, M','Concentration, 1 min',['Sorcerer','Wizard'],
 'Enlarge: grow Large (double size), +1d4 weapon damage, advantage STR checks and saves. Reduce: shrink Small, -1d4 weapon damage, disadvantage STR checks and saves. CON save to resist (unwilling).'],
['Enthrall',2,'Enc','1 action','60 ft','V, S','1 min',['Bard','Warlock'],
 'WIS save or fascinated (disadvantage on Perception checks to notice other creatures) for 1 minute, or until you stop speaking or are incapacitated.'],
['Find Steed',2,'Con','10 min','30 ft','V, S','Instantaneous',['Paladin'],
 'Summon a spirit as a steed (horse, pony, mastiff, or other beast). You share a bond; the steed can understand you. Dismissed to pocket dimension.'],
['Flame Blade',2,'Evo','1 bonus action','Self','V, S, M','Concentration, 10 min',['Druid'],
 'Summon a scimitar-like blade of fire. Melee spell attack: 3d6 fire damage. Sheds 10-ft bright light. Upcast: +1d6 per 2 slots above 2nd.'],
['Flaming Sphere',2,'Con','1 action','60 ft','V, S, M','Concentration, 1 min',['Druid','Wizard'],
 '5-ft-diameter sphere of fire (2d6 fire DEX save, half on save). Move it 30 ft as bonus action. Sheds 20-ft bright light. Upcast: +1d6 per slot.'],
['Gentle Repose',2,'Nec','1 action (ritual)','Touch','V, S, M','10 days',['Cleric','Wizard'],
 'Protect a corpse from decay and prevent it from becoming undead. The days of the spell count toward Raise Dead time limits.'],
['Gust of Wind',2,'Evo','1 action','Self (60-ft line)','V, S, M','Concentration, 1 min',['Druid','Sorcerer','Wizard'],
 '10-ft wide, 60-ft long line: STR save or pushed 15 ft away. Moving in is difficult terrain. Disperses gases and vapors.'],
['Heat Metal',2,'Tra','1 action','60 ft','V, S, M','Concentration, 1 min',['Bard','Druid'],
 'Metal object heats to burning. Creature in contact: CON save or 2d8 fire damage and drop the object (disadvantage on attacks/checks holding it). Bonus action to deal damage again. Upcast: +1d8 per slot.'],
['Hold Person',2,'Enc','1 action','60 ft','V, S, M','Concentration, 1 min',['Bard','Cleric','Druid','Sorcerer','Warlock','Wizard'],
 'WIS save or humanoid is paralyzed. Repeat save at end of each turn. Upcast: +1 target per slot.'],
['Invisibility',2,'Ill','1 action','Touch','V, S, M','Concentration, 1 hr',['Bard','Sorcerer','Warlock','Wizard'],
 'Creature becomes invisible until it attacks or casts a spell. Anything it carries is also invisible. Upcast: +1 target per slot.'],
['Knock',2,'Tra','1 action','60 ft','V','Instantaneous',['Wizard'],
 'Choose a locked door, lid, or chest: it opens. Suppresses arcane lock for 10 min. Loud knock audible 300 ft away.'],
['Lesser Restoration',2,'Abj','1 action','Touch','V, S','Instantaneous',['Bard','Cleric','Druid','Paladin','Ranger'],
 'End one disease or one condition: blinded, deafened, paralyzed, or poisoned.'],
['Levitate',2,'Tra','1 action','60 ft','V, S, M','Concentration, 10 min',['Sorcerer','Wizard'],
 'One creature or object (up to 500 lb): rises up to 20 ft and hovers. CON save (unwilling). Can move it 20 ft vertically per action.'],
['Locate Animals or Plants',2,'Div','1 action (ritual)','Self','V, S, M','Instantaneous',['Bard','Druid','Ranger'],
 'Name a specific kind of beast or plant: learn direction and distance to nearest one within 5 miles.'],
['Locate Object',2,'Div','1 action','Self','V, S, M','Concentration, 10 min',['Bard','Cleric','Druid','Paladin','Ranger','Wizard'],
 'Sense direction of a known object within 1000 ft. If a type is named (sword, gold, etc.) sense the nearest one. Lead blocks it.'],
['Magic Mouth',2,'Ill','1 min (ritual)','30 ft','V, S, M','Until dispelled',['Bard','Wizard'],
 'Imbue an object with a message (25 words, up to 10 min of audio). Set a trigger condition; the object then speaks the message.'],
['Magic Weapon',2,'Tra','1 bonus action','Touch','V, S','Concentration, 1 hr',['Paladin','Wizard'],
 'A nonmagical weapon becomes +1 magic. Upcast: +2 at 4th slot, +3 at 6th.'],
["Melf's Acid Arrow",2,'Evo','1 action','90 ft','V, S, M','Instantaneous',['Wizard'],
 'Ranged spell attack: 4d4 acid damage + 2d4 acid at end of target\'s next turn. Miss: 2d4 damage only. Upcast: +1d4 per slot (both parts).'],
['Mind Spike',2,'Div','1 action','60 ft','V','Instantaneous',['Sorcerer','Warlock','Wizard'],
 'WIS save or take 3d8 psychic damage (half on save) and you always know its location for 1 hr (can\'t be hidden by nondetection or similar). Upcast: +1d8 per slot.'],
['Mirror Image',2,'Ill','1 action','Self','V, S','1 min',['Sorcerer','Warlock','Wizard'],
 'Create 3 duplicates of yourself. When hit, roll d20: 6+ with 3 illusions (8+ with 2, 11+ with 1) the illusion is hit instead and destroyed.'],
['Misty Step',2,'Con','1 bonus action','Self','V','Instantaneous',['Sorcerer','Warlock','Wizard'],
 'Teleport up to 30 ft to a visible unoccupied space.'],
['Moonbeam',2,'Evo','1 action','120 ft','V, S, M','Concentration, 1 min',['Druid'],
 '5-ft radius, 40-ft tall cylinder of silvery light: CON save or 2d10 radiant damage (half on save). Shapechangers have disadvantage and become true form on fail. Move 60 ft/bonus action. Upcast: +1d10 per slot.'],
["Nystul's Magic Aura",2,'Ill','1 action','Touch','V, S, M','24 hr',['Wizard'],
 'Change how a creature or object registers to divination spells for 24 hr. Can mask its true nature or falsify creature type.'],
['Pass Without Trace',2,'Abj','1 action','Self','V, S, M','Concentration, 1 hr',['Druid','Ranger'],
 'You and up to 10 creatures within 30 ft each gain +10 to Stealth checks and leave no tracks.'],
['Phantasmal Force',2,'Ill','1 action','60 ft','V, S, M','Concentration, 1 min',['Bard','Sorcerer','Wizard'],
 'INT save or the creature experiences a phantasm (up to 10-ft cube): it believes it is real and interacts with it, taking 1d6 psychic damage per turn. Repeat save at end of each turn.'],
['Prayer of Healing',2,'Evo','10 min','30 ft','V','Instantaneous',['Cleric'],
 'Up to 6 creatures regain 2d8 + spellcasting modifier HP each. Upcast: +1d8 per slot.'],
['Protection from Poison',2,'Abj','1 action','Touch','V, S','1 hr',['Cleric','Druid','Paladin','Ranger'],
 'Neutralize one poison affecting the creature, and grant advantage on saves vs. poison and resistance to poison damage for 1 hr.'],
['Ray of Enfeeblement',2,'Nec','1 action','60 ft','V, S','Concentration, 1 min',['Warlock','Wizard'],
 'Ranged spell attack: STR-based attacks deal half damage. CON save at end of each turn to end.'],
['Rope Trick',2,'Tra','1 action','Touch','V, S, M','1 hr',['Wizard'],
 'Animate a 60-ft rope to rise and hang. A pocket extradimensional space at the top can hold up to 8 Medium or smaller creatures.'],
['See Invisibility',2,'Div','1 action','Self','V, S, M','1 hr',['Bard','Sorcerer','Wizard'],
 'See invisible creatures and objects; see into the Ethereal Plane up to 60 ft.'],
['Shatter',2,'Evo','1 action','60 ft','V, S, M','Instantaneous',['Bard','Sorcerer','Warlock','Wizard'],
 '10-ft radius sphere: CON save or 3d8 thunder damage (half on save). Inorganic creatures (stone, crystal, metal) have disadvantage. Objects take full damage. Upcast: +1d8 per slot.'],
['Silence',2,'Ill','1 action (ritual)','120 ft','V, S','Concentration, 10 min',['Bard','Cleric','Ranger'],
 '20-ft radius sphere: no sound created or passed. Immunity to thunder damage; spells with V component can\'t be cast inside.'],
['Spider Climb',2,'Tra','1 action','Touch','V, S, M','Concentration, 1 hr',['Sorcerer','Warlock','Wizard'],
 'Willing creature gains a climb speed equal to its walking speed and can climb difficult surfaces including ceilings.'],
['Spike Growth',2,'Tra','1 action','150 ft','V, S, M','Concentration, 10 min',['Druid','Ranger'],
 '20-ft radius: ground becomes difficult terrain. 2d4 piercing damage per 5 ft of movement through it. Disguised as normal ground.'],
['Spiritual Weapon',2,'Evo','1 bonus action','60 ft','V, S','1 min',['Cleric'],
 'Create a floating weapon. Bonus action: melee spell attack vs. adjacent creature for 1d8 + spellcasting mod force damage. Move up to 20 ft. Upcast: +1d8 per 2 slots above 2nd.'],
['Suggestion',2,'Enc','1 action','30 ft','V, M','Concentration, 8 hr',['Bard','Sorcerer','Warlock','Wizard'],
 'WIS save or follow a reasonable suggestion (not harmful to itself). Suggest up to 2 sentences. Spell ends once done or 8 hr pass.'],
['Warding Bond',2,'Abj','1 action','Touch','V, S, M','1 hr',['Cleric'],
 'You and a willing creature: it gains +1 AC and saving throws, and resistance to all damage. But you take the same damage it takes. 60-ft range required.'],
['Web',2,'Con','1 action','60 ft','V, S, M','Concentration, 1 hr',['Sorcerer','Wizard'],
 '20-ft cube of webs: difficult terrain; creatures must make DEX saves or be restrained (STR/DEX check to escape). Flammable.'],
['Zone of Truth',2,'Enc','1 action','60 ft','V, S','10 min',['Bard','Cleric','Paladin'],
 '15-ft radius sphere: CHA save or can\'t speak deliberate lies. Knows it\'s affected.'],

// ── Level 3 ─────────────────────────────────────────────────────────────────
['Animate Dead',3,'Nec','1 min','10 ft','V, S, M','Instantaneous',['Cleric','Wizard'],
 'Turn a corpse or pile of bones into a skeleton or zombie under your control (for 24 hr). Command with bonus action. Control up to 4 total. Upcast: +2 undead per slot.'],
['Bestow Curse',3,'Nec','1 action','Touch','V, S','Concentration, 1 min',['Bard','Cleric','Wizard'],
 'WIS save or cursed. Choose: disadvantage on ability checks/saves with one ability, disadvantage on attacks vs. you, WIS save each turn or waste action, +1d8 necrotic damage from your attacks. Upcast: 8 hr at 4th, 24 hr at 5th+, no concentration at 7th+.'],
['Blink',3,'Tra','1 action','Self','V, S','1 min',['Sorcerer','Wizard'],
 'Roll d20 at end of each turn: on 11+, vanish to Ethereal Plane until start of next turn (avoiding all attacks and effects).'],
['Call Lightning',3,'Con','1 action','120 ft','V, S','Concentration, 10 min',['Druid'],
 '100-ft tall cylinder, 5-ft radius point of origin. Once per turn, call a bolt as action: DEX save or 3d10 lightning damage in 5-ft radius (half on save). In storm: 4d10. Upcast: +1d10 per slot.'],
['Clairvoyance',3,'Div','10 min','1 mile','V, S, M','Concentration, 10 min',['Bard','Cleric','Sorcerer','Wizard'],
 'Create invisible sensor within 1 mile (known location). Hear or see through it (switching as action). Detect Magic can detect it.'],
['Conjure Animals',3,'Con','1 action','60 ft','V, S','Concentration, 1 hr',['Druid','Ranger'],
 'Summon: 1 CR 2 beast, 2 CR 1, 4 CR 1/2, or 8 CR 1/4. Friendly to you; acts on your initiative. Upcast: twice as many at 5th, three times at 7th.'],
['Counterspell',3,'Abj','1 reaction','60 ft','S','Instantaneous',['Sorcerer','Warlock','Wizard'],
 'Reaction when a creature casts a spell: automatically counter spells of 3rd level or lower; higher requires ability check DC 10 + spell level (spellcasting modifier). Upcast: automatically counter higher-level spells matching the slot.'],
['Daylight',3,'Evo','1 action','60 ft','V, S','1 hr',['Cleric','Druid','Paladin','Ranger','Sorcerer'],
 '60-ft radius sphere of sunlight. Dispels darkness created by spells of 3rd level or lower. Can be cast on an object (covered to suppress).'],
['Dispel Magic',3,'Abj','1 action','120 ft','V, S','Instantaneous',['Bard','Cleric','Druid','Paladin','Sorcerer','Warlock','Wizard'],
 'End one spell of 3rd level or lower on a target automatically; higher levels require ability check DC 10 + spell level. Upcast: auto-end spells of that slot level or lower.'],
['Fear',3,'Ill','1 action','Self (30-ft cone)','V, S, M','Concentration, 1 min',['Bard','Sorcerer','Warlock','Wizard'],
 'WIS save or drop held items and be frightened; must Dash away. Save at end of each turn. Ends on success.'],
['Fireball',3,'Evo','1 action','150 ft','V, S, M','Instantaneous',['Sorcerer','Wizard'],
 '20-ft radius sphere: DEX save or 8d6 fire damage (half on save). Spreads around corners. Ignites flammable objects. Upcast: +1d6 per slot.'],
['Fly',3,'Tra','1 action','Touch','V, S, M','Concentration, 10 min',['Sorcerer','Warlock','Wizard'],
 'Willing creature gains flying speed of 60 ft. Upcast: +1 target per slot.'],
['Gaseous Form',3,'Tra','1 action','Touch','V, S, M','Concentration, 1 hr',['Sorcerer','Warlock','Wizard'],
 'Turn willing creature into a misty cloud (fly 10 ft, hover). Resistance to nonmagical damage; immune to prone, grappled. Can\'t attack or cast spells.'],
['Glyph of Warding',3,'Abj','1 hr','Touch','V, S, M','Until dispelled or triggered',['Bard','Cleric','Wizard'],
 'Inscribe a glyph. Triggered by conditions you set. Blast Glyph: 5d8 damage in 20-ft sphere. Spell Glyph: store a spell of 3rd level or lower (fires when triggered).'],
['Haste',3,'Tra','1 action','30 ft','V, S, M','Concentration, 1 min',['Sorcerer','Wizard'],
 'One willing creature: doubled speed, +2 AC, advantage on DEX saves, gains an additional action (limited: Attack×1, Dash, Disengage, Hide, Use Object). Lethargy after: can\'t move or act for 1 turn.'],
['Hypnotic Pattern',3,'Ill','1 action','120 ft','V, S, M','Concentration, 1 min',['Bard','Sorcerer','Warlock','Wizard'],
 '30-ft cube: WIS save or charmed and incapacitated. Ends per creature if they take damage or someone uses action to snap them out of it.'],
['Lightning Bolt',3,'Evo','1 action','Self (100-ft line)','V, S, M','Instantaneous',['Sorcerer','Wizard'],
 '5-ft-wide, 100-ft line: DEX save or 8d6 lightning damage (half on save). Ignites flammable objects. Upcast: +1d6 per slot.'],
['Magic Circle',3,'Abj','1 min','10 ft','V, S, M','1 hr',['Cleric','Paladin','Warlock','Wizard'],
 '10-ft-radius, 20-ft-tall circle. Choose aberrations/celestials/elementals/fey/fiends/undead: chosen type can\'t enter or use mental abilities/charm/possession on those inside. Can reverse to trap inside. Upcast: +1 hr per slot.'],
['Major Image',3,'Ill','1 action','120 ft','V, S, M','Concentration, 10 min',['Bard','Sorcerer','Warlock','Wizard'],
 '20-ft cube illusion: sight, sound, smell, temperature. INT (Investigation) vs. spell save DC. Can be made permanent with 6th-level slot.'],
['Mass Healing Word',3,'Evo','1 bonus action','60 ft','V','Instantaneous',['Cleric'],
 'Up to 6 visible creatures each regain 1d4 + spellcasting mod HP. Upcast: +1d4 per slot.'],
['Nondetection',3,'Abj','1 action','Touch','V, S, M','8 hr',['Bard','Ranger','Wizard'],
 'Target can\'t be targeted by Detect Magic, Locate Object/Creature, scrying spells, or similar magic.'],
['Plant Growth',3,'Tra','1 action','150 ft','V, S','Instantaneous or 8 hr',['Bard','Druid','Ranger'],
 'Instant: 100-ft radius dense overgrowth (difficult terrain, 4 ft of movement per 1 ft). Overnight: area becomes fertile for 1 year.'],
['Protection from Energy',3,'Abj','1 action','Touch','V, S','Concentration, 1 hr',['Cleric','Druid','Ranger','Sorcerer','Wizard'],
 'Willing creature has resistance to one damage type: acid, cold, fire, lightning, or thunder.'],
['Remove Curse',3,'Abj','1 action','Touch','V, S','Instantaneous',['Cleric','Paladin','Warlock','Wizard'],
 'End all curses on one creature or object. If the object is a cursed magic item, the curse ends but it returns if attuned.'],
['Revivify',3,'Nec','1 action','Touch','V, S, M (300 gp diamond)','Instantaneous',['Cleric','Paladin'],
 'Restore life to a creature dead for no more than 1 minute. Returns with 1 HP. Diamonds are consumed.'],
['Sending',3,'Evo','1 action','Unlimited','V, S, M','1 round',['Bard','Cleric','Wizard'],
 'Send a message of 25 words to a familiar creature anywhere on the same plane. It can reply with 25 words.'],
['Sleet Storm',3,'Con','1 action','150 ft','V, S, M','Concentration, 1 min',['Druid','Sorcerer','Wizard'],
 '40-ft radius, 20-ft tall: freezing rain turns area into difficult terrain and heavily obscures it. Concentration to cast spells (DC 10 CON save). Slippery ground (DEX save DC 10 or fall prone).'],
['Slow',3,'Tra','1 action','120 ft','V, S, M','Concentration, 1 min',['Sorcerer','Wizard'],
 '40-ft cube: WIS save or speed halved, -2 AC and DEX saves, can\'t use reactions, only one action or bonus action per turn. Repeat save at end of each turn.'],
['Speak with Dead',3,'Nec','1 action','10 ft','V, S, M','10 min',['Bard','Cleric'],
 'Ask up to 5 questions of a corpse (dead < 10 years, with a mouth). Answers are limited to what the creature knew in life and are truthful.'],
['Speak with Plants',3,'Tra','1 action','Self (30-ft radius)','V, S','10 min',['Bard','Druid','Ranger'],
 'Plants can understand you and respond (audibly and in limited motion). Ask about events in the past day.'],
['Spirit Guardians',3,'Con','1 action','Self (15-ft radius)','V, S, M','Concentration, 10 min',['Cleric'],
 '15-ft radius: choose radiant/necrotic. Speed of creatures in aura is halved; WIS save or 3d8 damage when they enter or start turn (half on save). Upcast: +1d8 per slot.'],
['Stinking Cloud',3,'Con','1 action','90 ft','V, S, M','Concentration, 1 min',['Bard','Sorcerer','Wizard'],
 '20-ft radius sphere of yellowish fog, heavily obscured. CON save or waste action on your turn retching.'],
['Tongues',3,'Div','1 action','Touch','V, M','1 hr',['Bard','Cleric','Sorcerer','Warlock','Wizard'],
 'Understand any spoken language and be understood by any creature that has a language.'],
['Vampiric Touch',3,'Nec','1 action','Self','V, S','Concentration, 1 min',['Warlock','Wizard'],
 'Melee spell attack: 3d6 necrotic damage; regain HP equal to half the damage dealt. Upcast: +1d6 per slot.'],
['Water Breathing',3,'Tra','1 action (ritual)','30 ft','V, S, M','24 hr',['Druid','Ranger','Sorcerer','Wizard'],
 'Up to 10 creatures can breathe underwater for 24 hr.'],
['Water Walk',3,'Tra','1 action (ritual)','30 ft','V, S, M','1 hr',['Cleric','Druid','Ranger','Sorcerer'],
 'Up to 10 creatures walk on liquid as if solid ground. Aquatic creatures must make STR save to avoid being pulled to the surface.'],
['Wind Wall',3,'Evo','1 action','120 ft','V, S, M','Concentration, 1 min',['Druid','Ranger'],
 '50-ft long, 15-ft high wall of wind: 3d8 bludgeoning STR save (half on save), disperses gas/vapor, blocks nonmagical ranged attacks, small creatures pushed back.'],

// ── Level 4 ─────────────────────────────────────────────────────────────────
['Arcane Eye',4,'Div','1 action','30 ft','V, S, M','Concentration, 1 hr',['Wizard'],
 'Invisible, magical eye appears and lasts 1 hr. Darkvision 30 ft. Move up to 30 ft per action. Pass through tiny gaps.'],
['Banishment',4,'Abj','1 action','60 ft','V, S, M','Concentration, 1 min',['Cleric','Paladin','Sorcerer','Warlock','Wizard'],
 'CHA save or banished. Native-plane creatures vanish until concentration ends (then return). Extraplanar creatures are sent home permanently if concentration holds 1 min. Upcast: +1 target per slot.'],
['Blight',4,'Nec','1 action','30 ft','V, S','Instantaneous',['Druid','Sorcerer','Warlock','Wizard'],
 'CON save or take 8d8 necrotic damage (half on save). Plants auto-fail and take max damage. Upcast: +1d8 per slot.'],
['Compulsion',4,'Enc','1 action','30 ft','V, S','Concentration, 1 min',['Bard'],
 'WIS save or must move in a direction you specify on each of its turns (doesn\'t provoke AoOs). Can\'t be forced toward obvious hazards.'],
['Confusion',4,'Enc','1 action','90 ft','V, S, M','Concentration, 1 min',['Bard','Druid','Sorcerer','Wizard'],
 '10-ft radius sphere: WIS save or behavior randomized (d10 each turn: stand still, flee, attack nearest creature, or act normally). Repeat save at end of each turn. Upcast: +5 ft radius per slot.'],
['Control Water',4,'Tra','1 action','300 ft','V, S, M','Concentration, 10 min',['Cleric','Druid','Wizard'],
 'Flood (raise 20 ft), Part Water (create 20-ft-wide, 20-ft-deep trench), Redirect Flow, Whirlpool (25-ft-radius, 50-ft-tall; STR save or 2d8 bludgeoning and restrained).'],
['Death Ward',4,'Abj','1 action','Touch','V, S','8 hr',['Cleric','Paladin'],
 'If the creature would drop to 0 HP, it instead drops to 1 HP and the spell ends. Also nullifies effects that kill instantly.'],
['Dimension Door',4,'Con','1 action','500 ft','V','Instantaneous',['Bard','Sorcerer','Warlock','Wizard'],
 'Teleport up to 500 ft to a location you visualize. Can bring one willing Medium or smaller creature (or objects up to your carrying capacity).'],
['Divination',4,'Div','1 action (ritual)','Self','V, S, M','Instantaneous',['Cleric'],
 'Contact your deity with a question about a goal, event, or activity. Truthful answer: Yes, No, or a cryptic phrase. 1/long rest (25% mislead if used more).'],
['Dominate Beast',4,'Enc','1 action','60 ft','V, S','Concentration, 1 min',['Druid','Sorcerer'],
 'WIS save or charmed: use action to command the beast telepathically. It takes reactions on its own. Repeat save when it takes damage. Upcast: 10 min at 5th (no conc), 1 hr at 6th, 8 hr at 7th+.'],
["Evard's Black Tentacles",4,'Con','1 action','90 ft','V, S, M','Concentration, 1 min',['Wizard'],
 '20-ft square: difficult terrain; wriggling tentacles attempt to grapple (STR/DEX save or restrained and 3d6 bludgeoning per turn).'],
['Fabricate',4,'Tra','10 min','120 ft','V, S','Instantaneous',['Wizard'],
 'Transform raw materials into a finished item (up to 10 cu ft of wood/stone or 1 cu ft of metal). Requires artisan proficiency for complex items. Magical raw materials remain magical.'],
['Fire Shield',4,'Evo','1 action','Self','V, S, M','10 min',['Wizard'],
 'Flames wreathe you. Warm shield: cold resistance; attackers take 2d8 fire. Chill shield: fire resistance; attackers take 2d8 cold.'],
['Freedom of Movement',4,'Abj','1 action','Touch','V, S, M','1 hr',['Bard','Cleric','Druid','Ranger'],
 'Movement can\'t be reduced by magical effects or difficult terrain; immune to paralysis and restraint; can use 5 ft of movement to escape grapple or restrain.'],
['Greater Invisibility',4,'Ill','1 action','Touch','V, S','Concentration, 1 min',['Bard','Sorcerer','Wizard'],
 'Creature is invisible for the duration, even while attacking or casting spells.'],
['Guardian of Faith',4,'Con','1 action','30 ft','V','8 hr',['Cleric'],
 'Large spectral guardian appears. Hostile creatures within 10 ft must make DEX save or take 20 radiant damage (half on save). After dealing 60 total damage, it vanishes.'],
['Hallucinatory Terrain',4,'Ill','10 min','300 ft','V, S, M','24 hr',['Bard','Druid','Warlock','Wizard'],
 'Make a 150-ft cube of natural terrain look, sound, and smell like another natural terrain. INT Investigation vs. spell save DC to see through on physical interaction.'],
['Ice Storm',4,'Evo','1 action','300 ft','V, S, M','Instantaneous',['Druid','Sorcerer','Wizard'],
 '20-ft-radius, 40-ft tall cylinder: 2d8 bludgeoning + 4d6 cold damage (DEX save for half); area becomes difficult terrain until end of next turn. Upcast: +1d8 bludgeoning per slot.'],
['Locate Creature',4,'Div','1 action','Self','V, S, M','Concentration, 1 hr',['Bard','Cleric','Druid','Paladin','Ranger','Wizard'],
 'Sense direction of a specific creature or a type of creature within 1000 ft. Lead blocks it. Running water interrupts it.'],
["Mordenkainen's Faithful Hound",4,'Con','1 action','30 ft','V, S, M','8 hr',['Wizard'],
 'Invisible hound guards a location. Any creature it detects within 5 ft triggers barking. It attacks: +9 to attack, 4d8 piercing damage. Stays up to 8 hr.'],
["Otiluke's Resilient Sphere",4,'Evo','1 action','30 ft','V, S, M','Concentration, 1 min',['Wizard'],
 'DEX save or enclosed in 10-ft sphere of force (immune to all damage, can\'t be affected or affect environment). Can be rolled. STR check (DC = spell save DC) to crush.'],
['Phantasmal Killer',4,'Ill','1 action','120 ft','V, S','Concentration, 1 min',['Wizard'],
 'WIS save or frightened. At the start of each of its turns: WIS save or take 4d10 psychic damage. Ends on success. Upcast: +1d10 per slot.'],
['Polymorph',4,'Tra','1 action','60 ft','V, S, M','Concentration, 1 hr',['Bard','Cleric','Druid','Sorcerer','Wizard'],
 'WIS save (unwilling creatures) or transform into a beast of CR ≤ target\'s level/CR. Retains personality but not memories while in form. Drops to 0 HP = reverts.'],
['Stone Shape',4,'Tra','1 action','Touch','V, S, M','Instantaneous',['Cleric','Druid','Wizard'],
 'Shape stone up to 5 cu ft into any form you desire. Create a rough passage, seal a door, shape a crude statue, etc.'],
['Stoneskin',4,'Abj','1 action','Touch','V, S, M (100 gp diamond)','Concentration, 1 hr',['Druid','Ranger','Sorcerer','Wizard'],
 'A willing creature gains resistance to nonmagical bludgeoning, piercing, and slashing damage for the duration.'],
['Wall of Fire',4,'Evo','1 action','120 ft','V, S, M','Concentration, 1 min',['Druid','Sorcerer','Wizard'],
 'Up to 60-ft-long, 20-ft-tall, 1-ft-thick wall or 20-ft-diameter ring. One side you choose deals 5d8 fire damage on entry or start of turn there. Upcast: +1d8 per slot.'],

// ── Level 5 ─────────────────────────────────────────────────────────────────
['Animate Objects',5,'Tra','1 action','120 ft','V, S','Concentration, 1 min',['Bard','Sorcerer','Wizard'],
 'Animate up to 10 nonmagical objects (Tiny to Large). Stats by size. Bonus action to command. Can\'t animate worn/carried objects. Upcast: +2 objects per slot.'],
['Antilife Shell',5,'Abj','1 action','Self (10-ft radius)','V, S','Concentration, 1 hr',['Druid'],
 'Animated, living creatures can\'t enter a 10-ft radius around you (construct, undead can).'],
['Bigby\'s Hand',5,'Evo','1 action','120 ft','V, S, M','Concentration, 1 min',['Wizard'],
 'Large hand of force appears. Bonus action to command: Clenched Fist (4d8 force, melee spell attack), Forceful Hand (push 5 ft/5 pts of speed), Grasping Hand (grapple: STR vs. spell save DC, 2d6/turn), Interposing Hand (+4 AC from one attacker). Upcast: +2d8/1d6 per slot.'],
['Circle of Power',5,'Abj','1 action','Self (30-ft radius)','V','Concentration, 10 min',['Paladin'],
 '30-ft aura: allies have advantage on saving throws against spells and magical effects; on success vs. a save-for-half spell, take no damage.'],
['Cloudkill',5,'Con','1 action','120 ft','V, S','Concentration, 10 min',['Sorcerer','Wizard'],
 '20-ft-radius sphere of toxic yellow-green fog. CON save or 5d8 poison damage (half on save). Spreads around corners, sinks. Move 10 ft from you per round. Upcast: +1d8 per slot.'],
['Commune',5,'Div','1 min (ritual)','Self','V, S, M','1 min',['Cleric'],
 'Contact your divine patron. Ask up to 3 Yes/No questions (truthfully answered). 1/long rest (25% chance of no answer if used more).'],
['Commune with Nature',5,'Div','1 min (ritual)','Self','V, S','Instantaneous',['Druid','Ranger'],
 'Gain intimate knowledge of the land within 3 miles (6 miles underground). Know terrain, bodies of water, prevalent plants/animals, powerful planar/celestial/fey/undead presences, influence of civilization, and creatures of a type you specify.'],
['Cone of Cold',5,'Evo','1 action','Self (60-ft cone)','V, S, M','Instantaneous',['Sorcerer','Wizard'],
 '60-ft cone: CON save or 8d8 cold damage (half on save). Kills → frozen statue (shatters into pieces if hit). Upcast: +1d8 per slot.'],
['Conjure Elemental',5,'Con','1 min','90 ft','V, S, M','Concentration, 1 hr',['Druid','Wizard'],
 'Summon an elemental (Air, Earth, Fire, or Water) of CR 5 or lower. If concentration breaks, the elemental becomes hostile.'],
['Contact Other Plane',5,'Div','1 min (ritual)','Self','V','1 min',['Warlock','Wizard'],
 'Contact an otherworldly being for up to 5 Yes/No questions. INT DC 15 save or take 6d6 psychic damage and gain short-term madness.'],
['Contagion',5,'Nec','1 action','Touch','V, S','7 days',['Cleric','Druid'],
 'Melee spell attack: disease; CON save at end of each of target\'s turns for 3 turns — 3 fails: sick for 7 days (Blinding Sickness, Filth Fever, Flesh Rot, Mindfire, Seizure, Slimy Doom). 3 successes: immune for 24 hr.'],
['Creation',5,'Ill','1 min','30 ft','V, S, M','Special',['Sorcerer','Wizard'],
 'Create nonliving matter up to 5 cu ft of vegetable matter (duration 1 day), stone/crystal/base metal (12 hr), precious metals (1 hr), or adamantine/mithral (1 min). Upcast: +5 cu ft per slot.'],
['Destructive Wave',5,'Evo','1 action','Self (30-ft radius)','V','Instantaneous',['Paladin'],
 '30-ft radius: CON save or 5d6 thunder + 5d6 radiant/necrotic damage and knocked prone (half on save, not prone).'],
['Dispel Evil and Good',5,'Abj','1 action','Self','V, S, M','Concentration, 1 min',['Cleric','Paladin'],
 'Celestials, elementals, fey, fiends, undead have disadvantage on attacks vs. you. 3 options: Dismissal (banish extraplanar creature), Break Enchantment (end charm/fear/possession), Dismissal using melee attack.'],
['Dominate Person',5,'Enc','1 action','60 ft','V, S','Concentration, 1 min',['Bard','Sorcerer','Wizard'],
 'WIS save or charmed humanoid: control via telepathy. Repeat save when it takes damage. Upcast: 10 min at 6th, 1 hr at 7th, 8 hr at 8th+.'],
['Dream',5,'Ill','1 min','Special','V, S, M','8 hr',['Bard','Warlock','Wizard'],
 'Enter dreams of a sleeping target anywhere on same plane. Can shape dreams. WIS save or suffer dream haunt: fail to benefit from the rest, 3d6 psychic damage. Can be used to send peaceful dreams.'],
['Flame Strike',5,'Evo','1 action','60 ft','V, S, M','Instantaneous',['Cleric'],
 '10-ft radius, 40-ft tall cylinder: DEX save or 4d6 fire + 4d6 radiant damage (half on save). Upcast: +1d6 of each per slot.'],
['Geas',5,'Enc','1 min','60 ft','V','30 days',['Bard','Cleric','Druid','Paladin','Wizard'],
 'WIS save or charmed: follow a command (not harmful). 5d10 psychic damage for acting against it. Upcast: 1 year at 7th; permanent at 9th.'],
['Greater Restoration',5,'Abj','1 action','Touch','V, S, M (100 gp diamond dust)','Instantaneous',['Bard','Cleric','Druid'],
 'End one of: charm, petrification, curse, one ability score reduction, or reduction to HP max.'],
['Hallow',5,'Evo','24 hr','Touch','V, S, M (1000 gp herbs/oils)','Until dispelled',['Cleric'],
 'Designate an area up to 60-ft radius as hallowed. Choose a type (celestials/etc.) that can\'t enter or charm/possess within. Add one extra effect (silence, daylight, fear, etc.).'],
['Hold Monster',5,'Enc','1 action','90 ft','V, S, M','Concentration, 1 min',['Bard','Sorcerer','Warlock','Wizard'],
 'WIS save or any creature (including undead) is paralyzed. Repeat save at end of each turn. Upcast: +1 target per slot.'],
['Insect Plague',5,'Con','1 action','300 ft','V, S, M','Concentration, 10 min',['Cleric','Druid','Sorcerer'],
 '20-ft sphere of locusts, heavily obscured. CON save or 4d10 piercing damage (half on save) on entry or start of turn. Upcast: +1d10 per slot.'],
['Legend Lore',5,'Div','10 min','Self','V, S, M','Instantaneous',['Bard','Cleric','Wizard'],
 'Learn lore about a person, place, or object: legends, myths, histories, or tales related to it. Gain fragmentary mythic information if obscure.'],
['Mass Cure Wounds',5,'Evo','1 action','60 ft','V, S','Instantaneous',['Bard','Cleric','Druid'],
 'Up to 6 visible creatures each regain 3d8 + spellcasting mod HP. Upcast: +1d8 per slot.'],
['Mislead',5,'Ill','1 action','Self','S','Concentration, 1 hr',['Bard','Wizard'],
 'Turn invisible while creating an illusory double at your current location. Use bonus action to move the double up to double your speed and speak through it.'],
['Modify Memory',5,'Enc','1 action','30 ft','V, S','Concentration, 1 min',['Bard','Wizard'],
 'WIS save or incapacitated (you alter its memory of up to 10 min within the last 24 hr). Can destroy, create, or change the memory. Upcast: 24 hr at 6th, 7 days at 7th, 30 days at 8th, any at 9th.'],
['Passwall',5,'Tra','1 action','30 ft','V, S, M','1 hr',['Wizard'],
 'Create a passage through a wood, plaster, or stone wall up to 20 ft deep, 5 ft wide, 8 ft tall. Creatures inside if the passage closes are pushed out.'],
['Planar Binding',5,'Abj','1 hr','60 ft','V, S, M (1000 gp gem dust)','24 hr',['Bard','Cleric','Druid','Wizard'],
 'Bind a celestial, elemental, fey, or fiend that has already been summoned to your service. CHA save or it must serve you for the duration. Upcast: 10 days at 6th, 30 days at 7th, 180 days at 8th, 1 year at 9th.'],
['Raise Dead',5,'Nec','1 hr','Touch','V, S, M (500 gp diamond)','Instantaneous',['Bard','Cleric','Paladin'],
 'Restore life to a creature dead ≤ 10 days (willing). Returns with 1 HP, minus 4 penalty to attacks/checks/saves (removed 1/day). Body needed. No effect on undead.'],
['Reincarnate',5,'Tra','1 hr','Touch','V, S, M (1000 gp oils)','Instantaneous',['Druid'],
 'Restore life to a creature dead ≤ 10 days. Roll d100 to determine the new body (human, elf, etc.). Gets that race\'s racial traits.'],
['Scrying',5,'Div','10 min','Self','V, S, M (1000 gp focus)','Concentration, 10 min',['Bard','Cleric','Druid','Warlock','Wizard'],
 'WIS save (modified by familiarity with the target) or spy through an invisible sensor near the creature. Can use action to look around the sensor.'],
['Seeming',5,'Ill','1 action','30 ft','V, S','8 hr',['Bard','Sorcerer','Wizard'],
 'Change appearance of any number of creatures within range. Each can look, sound, and smell different. INT Investigation vs. spell save DC.'],
['Telekinesis',5,'Tra','1 action','60 ft','V, S','Concentration, 10 min',['Sorcerer','Wizard'],
 'Move one creature or object (up to 1000 lb) up to 30 ft per action. Creature STR vs. spellcasting ability check; object can be moved up to 30 ft and held still.'],
['Teleportation Circle',5,'Con','1 min','10 ft','V, M','1 round',['Bard','Sorcerer','Wizard'],
 'Draw a sigil-ringed circle that teleports anyone who steps through it to a permanent teleportation circle (whose sequence of sigils you know) on the same plane.'],
['Tree Stride',5,'Con','1 action','Self','V, S','Concentration, 1 min',['Druid','Ranger'],
 'Enter a living tree and exit from another of the same species within 500 ft. Up to twice your speed per turn.'],
['Wall of Force',5,'Evo','1 action','120 ft','V, S, M','Concentration, 10 min',['Wizard'],
 'Invisible wall of force (up to 10 × 10-ft panels, curve into dome). Immune to all damage; only Disintegrate or Dispel Magic can end it. Nothing can physically pass.'],
['Wall of Stone',5,'Evo','1 action','120 ft','V, S, M','Concentration, 10 min',['Druid','Sorcerer','Wizard'],
 'Up to six 10×10-ft panels of stone (6 in thick), mergeable with existing stone. Can be made permanent. Creatures in a panel space make DEX save or are restrained.'],

// ── Level 6 ─────────────────────────────────────────────────────────────────
['Arcane Gate',6,'Con','1 action','500 ft','V, S','Concentration, 10 min',['Sorcerer','Warlock','Wizard'],
 'Linked pair of portals (up to 5-ft diameter) — step through one and emerge from the other. Distance between portals up to 500 ft.'],
['Blade Barrier',6,'Evo','1 action','90 ft','V, S','Concentration, 10 min',['Cleric'],
 '100-ft-long, 20-ft-high wall of whirling blades. DEX save or 6d10 slashing damage (half on save). Difficult terrain.'],
['Chain Lightning',6,'Evo','1 action','150 ft','V, S, M','Instantaneous',['Sorcerer','Wizard'],
 'Three lightning bolts (4 at 7th+): DEX save or 10d8 lightning damage (half on save). Can chain to different targets within 30 ft of each other. Upcast: +1 bolt per slot.'],
['Circle of Death',6,'Nec','1 action','150 ft','V, S, M','Instantaneous',['Sorcerer','Warlock','Wizard'],
 '60-ft radius sphere: CON save or 8d6 necrotic damage (half on save). Upcast: +2d6 per slot.'],
['Create Undead',6,'Nec','1 min','10 ft','V, S, M','Instantaneous',['Cleric','Warlock','Wizard'],
 'Create 3 ghouls from humanoid corpses. Control up to 3 at a time (ghasts at 7th, wights at 8th, mummies at 9th). Must maintain control by re-casting within 24 hr.'],
['Disintegrate',6,'Tra','1 action','60 ft','V, S, M','Instantaneous',['Sorcerer','Wizard'],
 'DEX save or 10d6+40 force damage. Reduces to 0 HP → dust (including nonmagical objects up to 10-ft cube). Upcast: +3d6 per slot.'],
['Eyebite',6,'Nec','1 action','Self','V, S','Concentration, 1 min',['Bard','Sorcerer','Warlock','Wizard'],
 'Choose one creature per turn as a bonus action. WIS save or: Asleep (unconscious until damaged/shaken), Panicked (frightened, must dash away), Sickened (disadvantage on attacks/checks).'],
['Find the Path',6,'Div','1 min','Self','V, S, M','Concentration, 1 day',['Bard','Cleric','Druid'],
 'Know the shortest direct route to a location on the same plane. Can navigate around obstacles.'],
['Flesh to Stone',6,'Tra','1 action','60 ft','V, S, M','Concentration, 1 min',['Warlock','Wizard'],
 'CON save or restrained (flesh hardens); 3 failures → petrified. 3 successes → immune for 24 hr. Reversed by Greater Restoration or Remove Curse.'],
['Globe of Invulnerability',6,'Abj','1 action','Self (10-ft radius)','V, S, M','Concentration, 1 min',['Sorcerer','Wizard'],
 '10-ft radius barrier: spells of 5th level or lower cast from outside can\'t affect anything inside. Upcast: increases to match slot level -1.'],
['Harm',6,'Nec','1 action','60 ft','V, S','Instantaneous',['Cleric'],
 'CON save or take 14d6 necrotic damage (half on save) and max HP reduced by amount of damage dealt (save: no HP reduction). Can\'t be reduced below 1.'],
['Heal',6,'Evo','1 action','60 ft','V, S','Instantaneous',['Cleric','Druid'],
 'Restore 70 HP to one creature; also end blinded, deafened, and diseased. Upcast: +10 HP per slot.'],
["Heroes' Feast",6,'Con','10 min','30 ft','V, S, M (1000 gp jeweled bowl)','Instantaneous',['Bard','Cleric','Druid'],
 'Up to 12 creatures partake in a feast: cured of all diseases/poison; immune to poison/fear; +2d10 max HP (for 24 hr); WIS saves with advantage.'],
["Irresistible Dance (Otto's)",6,'Enc','1 action','30 ft','V','Concentration, 1 min',['Bard','Wizard'],
 'Humanoid begins dancing (no save initially). WIS save each turn to end the effect. While dancing: -4 AC, disadvantage DEX saves, opponents have advantage on attacks vs. it.'],
['Magic Jar',6,'Nec','1 min','Self','V, S, M (500 gp gem)','Until dispelled',['Wizard'],
 'Transfer your soul to a gem container (up to 100 ft); possess a humanoid corpse/creature within 100 ft (CHA save). Can return to body or switch hosts.'],
['Mass Suggestion',6,'Enc','1 action','60 ft','V, M','24 hr',['Bard','Sorcerer','Warlock','Wizard'],
 'Up to 12 creatures: WIS save or follow a reasonable suggestion for 24 hr. Upcast: 10 days at 7th, 30 days at 8th, 1 year at 9th.'],
['Move Earth',6,'Tra','1 action','120 ft','V, S, M','Concentration, 2 hr',['Druid','Sorcerer','Wizard'],
 'Shape dirt, sand, or clay in a 40-ft cube. Dig trenches, create hills, reshape terrain. 10-ft of movement per action.'],
["Otiluke's Freezing Sphere",6,'Evo','1 action','300 ft','V, S, M','Instantaneous',['Wizard'],
 '60-ft-radius sphere: CON save or 10d6 cold damage (half on save). Freezes nonmagical water in area. Can hold the ball for up to 1 min and throw it.'],
['Programmed Illusion',6,'Ill','1 action','120 ft','V, S, M','Until dispelled',['Bard','Wizard'],
 'Create an illusion (up to 30-ft cube) that activates on a chosen trigger condition, plays for up to 5 minutes, then goes dormant.'],
['Sunbeam',6,'Evo','1 action','Self (60-ft line)','V, S, M','Concentration, 1 min',['Druid','Sorcerer','Wizard'],
 '5-ft wide, 60-ft line: CON save or 6d8 radiant damage and blinded until next turn (half damage, not blinded on save). Each action, cast another beam. Undead have disadvantage.'],
['True Seeing',6,'Div','1 action','Touch','V, S, M','1 hr',['Bard','Cleric','Sorcerer','Warlock','Wizard'],
 'The creature can see through illusions, see invisible creatures, sees into the Ethereal Plane, and reads the true form of shapeshifters.'],
['Wall of Ice',6,'Evo','1 action','120 ft','V, S, M','Concentration, 10 min',['Wizard'],
 '10-ft-tall, 1-ft-thick ice wall (up to 10 × 10-ft panels). CON save or 10d6 cold damage (half on save) for creatures in the path. Breaks into jagged shards when smashed.'],
['Wall of Thorns',6,'Con','1 action','120 ft','V, S, M','Concentration, 10 min',['Druid'],
 '60-ft-long, 10-ft-high wall of thorns. 7d8 piercing damage (DEX save for half) moving through. Difficult terrain.'],
['Word of Recall',6,'Con','1 action','5 ft','V','Instantaneous',['Cleric'],
 'Designate a sanctuary point in advance. Teleport yourself and up to 5 willing creatures there instantly.'],

// ── Level 7 ─────────────────────────────────────────────────────────────────
['Conjure Celestial',7,'Con','1 min','90 ft','V, S','Concentration, 1 hr',['Cleric'],
 'Summon a celestial (CR 4 or lower; CR 5+ at 9th slot) that is friendly to you. Acts on its own initiative.'],
['Delayed Blast Fireball',7,'Evo','1 action','150 ft','V, S, M','Concentration, 1 min',['Sorcerer','Wizard'],
 'Glowing bead stops at a point you choose. Explodes at end of concentration (or sooner by choice): 20-ft radius, DEX save or 12d6 fire damage (half on save). +1d6 per extra round held. Upcast: +1d6 per slot.'],
['Divine Word',7,'Evo','1 bonus action','30 ft','V','Instantaneous',['Cleric'],
 'Speak a divine utterance. Creatures with ≤ 50 HP are deafened; ≤ 40 HP blinded; ≤ 30 HP stunned; ≤ 20 HP killed instantly. Celestials, elementals, fey, and fiends also banished if they fail a CHA save.'],
['Etherealness',7,'Tra','1 action','Self','V, S','Up to 8 hr',['Bard','Cleric','Sorcerer','Warlock','Wizard'],
 'Enter the Ethereal Plane for the duration. Move in any direction. See and hear the Material Plane, but only dimly. Upcast: +2 targets per slot at 8th–9th.'],
['Finger of Death',7,'Nec','1 action','60 ft','V, S','Instantaneous',['Sorcerer','Warlock','Wizard'],
 'CON save or 7d8+30 necrotic damage (half on save). If this kills a humanoid, it rises as a zombie under your permanent command.'],
['Fire Storm',7,'Evo','1 action','150 ft','V, S','Instantaneous',['Cleric','Druid','Sorcerer'],
 'Up to 10 × 10-ft cubes of fire: DEX save or 7d10 fire damage (half on save). Plants auto-fail. Can spare creatures of your choice.'],
['Forcecage',7,'Evo','1 action','100 ft','V, S, M (1500 gp ruby dust)','1 hr',['Bard','Warlock','Wizard'],
 'Create a cagework of force (20-ft cube, barred) or a solid box (10-ft cube). Trapped until spell ends or dispelled. CHA save to teleport out.'],
['Mirage Arcane',7,'Ill','10 min','Sight','V, S','10 days',['Bard','Druid','Wizard'],
 'Alter terrain of up to 1 square mile to look, sound, smell, and feel like another natural terrain. INT Investigation to see through.'],
['Plane Shift',7,'Con','1 action','Touch','V, S, M (250 gp tuning fork)','Instantaneous',['Cleric','Druid','Sorcerer','Warlock','Wizard'],
 'Transport up to 8 willing creatures to a plane of your choice. Or: melee spell attack to send an unwilling creature to another plane (CHA save to resist).'],
['Prismatic Spray',7,'Evo','1 action','Self (60-ft cone)','V, S','Instantaneous',['Sorcerer','Wizard'],
 '60-ft cone: DEX save or roll d8 for color effect: 1 Fire 10d6, 2 Acid 10d6, 3 Lightning 10d6, 4 Cold 10d6, 5 Poison 10d6, 6 Restrained then Petrified (CON save), 7 Blinded then Turned to Stone (CON save), 8 Transported to another plane (CHA save).'],
['Project Image',7,'Ill','1 action','500 miles','V, S, M','Concentration, 1 day',['Bard','Wizard'],
 'Create an illusory double anywhere within range. You can see/hear through it and cast spells through it as if you were there.'],
['Regenerate',7,'Tra','1 min','Touch','V, S, M','1 hr',['Bard','Cleric','Druid'],
 'Target regains 4d8+15 HP; regrows lost limbs over 2 minutes; regains 1 HP per minute for the duration.'],
['Resurrection',7,'Nec','1 hr','Touch','V, S, M (1000 gp diamond)','Instantaneous',['Bard','Cleric'],
 'Restore life to a creature dead for up to 100 years. The creature returns with all HP. Reduces MAX HP and ability scores by 4 (removed after 4 days).'],
['Reverse Gravity',7,'Tra','1 action','100 ft','V, S, M','Concentration, 1 min',['Druid','Sorcerer','Wizard'],
 'All creatures and objects in a 50-ft-radius, 100-ft-tall cylinder (unless anchored) fall upward for the duration. DEX save when cast or when reaching the top.'],
['Symbol',7,'Abj','1 min','Touch','V, S, M (1000 gp mercury/phosphorus)','Until dispelled/triggered',['Bard','Cleric','Wizard'],
 'Inscribe a glyph. Trigger: Death, Discord, Fear, Hopelessness, Insanity, Pain, Sleep, or Stunning — each affecting creatures of up to 10th level.'],
['Teleport',7,'Con','1 action','10 ft','V','Instantaneous',['Bard','Sorcerer','Wizard'],
 'Teleport yourself and up to 8 willing creatures (or 1000 lb of objects) to a destination on same plane. Familiarity determines accuracy (Permanent Circle = on target; Very Familiar = 1d10 roll).'],
['Whirlwind',7,'Evo','1 action','300 ft','V, M','Concentration, 1 min',['Druid','Sorcerer','Wizard'],
 '10-ft-radius, 30-ft-tall cylinder of swirling wind. Creatures within make STR save or take 10d6 bludgeoning and are restrained. Can move cylinder 30 ft/action.'],

// ── Level 8 ─────────────────────────────────────────────────────────────────
["Abi-Dalzim's Horrid Wilting",8,'Nec','1 action','150 ft','V, S, M','Instantaneous',['Sorcerer','Wizard'],
 '30-ft cube: CON save or 12d8 necrotic damage (half on save). Plants and water elementals auto-fail and can\'t resist. Undead unaffected.'],
['Antimagic Field',8,'Abj','1 action','Self (10-ft radius)','V, S, M','Concentration, 1 hr',['Cleric','Wizard'],
 '10-ft-radius sphere: all magic is suppressed within. Spells can\'t be cast; magical items cease to function. You are unaffected.'],
['Clone',8,'Nec','1 hr','Touch','V, S, M (1500 gp materials + body tissue)','Instantaneous',['Wizard'],
 'Grow a duplicate of a creature that matures in 120 days (or as little as 24 with enough material). When the original dies, its soul transfers to the clone.'],
['Control Weather',8,'Tra','10 min','Self (5-mile radius)','V, S, M','Concentration, 8 hr',['Cleric','Druid','Wizard'],
 'Change weather in a 5-mile radius: precipitation, temperature, and wind. Changes take 1d4 × 10 minutes to take effect.'],
['Demiplane',8,'Con','1 action','60 ft','S','1 hr',['Warlock','Wizard'],
 'Create a shadowy door to a 30-ft-cube demiplane. Up to 30 objects or creatures can enter. Anything inside when the door disappears is trapped there.'],
['Dominate Monster',8,'Enc','1 action','60 ft','V, S','Concentration, 1 hr',['Bard','Sorcerer','Warlock','Wizard'],
 'WIS save or any creature type (including undead) is charmed: control via telepathy. Repeat save when it takes damage.'],
['Earthquake',8,'Evo','1 action','500 ft','V, S, M','Concentration, 1 min',['Cleric','Druid','Sorcerer'],
 '100-ft-radius tremor: difficult terrain; concentration checks (DC 15); structures take damage; fissures (10% chance per turn, DEX save or fall in).'],
['Feeblemind',8,'Enc','1 action','150 ft','V, S, M','Instantaneous',['Bard','Druid','Warlock','Wizard'],
 'INT save or INT and CHA drop to 1 for 30 days. Can\'t cast spells or use magic items. INT check (DC = spell save DC) every 30 days to end.'],
['Glibness',8,'Tra','1 action','Self','V','1 hr',['Bard','Warlock'],
 'Replace any CHA check roll with a 15. The spell also makes magic unable to determine if you\'re lying.'],
['Holy Aura',8,'Abj','1 action','Self (30-ft radius)','V, S, M (5000 gp relic)','Concentration, 1 min',['Cleric'],
 'Allies glow with dim light, have advantage on all saves, attackers have disadvantage. If a fiend or undead hits one, it must CON save or be blinded.'],
['Incendiary Cloud',8,'Con','1 action','150 ft','V, S','Concentration, 1 min',['Sorcerer','Wizard'],
 '20-ft-radius sphere of smoke: heavily obscured. DEX save or 10d8 fire damage (half on save) at start of your turns. Moves 10 ft away from you each turn.'],
['Maze',8,'Con','1 action','60 ft','V, S','Concentration, 10 min',['Wizard'],
 'Banish a creature to a labyrinthine demiplane. DC 20 INT check (DC 5 for minotaurs and labyrinthine creatures) to escape. Returns when it succeeds or spell ends.'],
['Mind Blank',8,'Abj','1 action','Touch','V, S','24 hr',['Bard','Wizard'],
 'Immunity to psychic damage, charm, emotion-reading, divination magic, and scrying.'],
['Power Word Stun',8,'Enc','1 action','60 ft','V','Instantaneous',['Bard','Sorcerer','Warlock','Wizard'],
 'If the target has 150 HP or fewer, it is stunned. CON save at end of each of its turns to end the effect.'],
['Sunburst',8,'Evo','1 action','150 ft','V, S, M','Instantaneous',['Druid','Sorcerer','Wizard'],
 '60-ft-radius sphere of sunlight: CON save or 12d6 radiant damage and blinded for 1 min (half, not blinded on save). Undead and oozes have disadvantage. Dispels magical darkness up to 8th level.'],
['Tsunami',8,'Con','1 min','Sight','V, S','Concentration, 6 rounds',['Druid'],
 '300-ft-long, 300-ft-high wall of water. Creatures in it: STR save or take 6d10 bludgeoning and be swept up. Wall moves 50 ft toward land each turn.'],

// ── Level 9 ─────────────────────────────────────────────────────────────────
['Astral Projection',9,'Nec','1 hr','10 ft','V, S, M (1100+ gp materials)','Special',['Cleric','Warlock','Wizard'],
 'You and up to 8 willing creatures project onto the Astral Plane, leaving silver-cord-tethered astral bodies. The astral body can enter other planes. Cord severed = death.'],
['Foresight',9,'Div','1 min','Touch','V, S, M','8 hr',['Bard','Druid','Warlock','Wizard'],
 'The creature can\'t be surprised; has advantage on all attack rolls, ability checks, and saving throws; and attack rolls against it have disadvantage.'],
['Gate',9,'Con','1 action','60 ft','V, S, M (5000 gp diamond)','Concentration, 1 min',['Cleric','Sorcerer','Wizard'],
 'Open a circular portal to another plane. A specific named creature on that plane must make CHA save or be drawn through. Portal is two-way.'],
['Imprisonment',9,'Abj','1 min','30 ft','V, S, M (500 gp/HD material)','Until dispelled',['Warlock','Wizard'],
 'WIS save or imprisoned. Choose: Burial (underground), Chaining (adamantine chains), Hedged Prison (demiplane), Minimus Containment (gem), Slumber (endless sleep). Each has a specific means of breaking it.'],
['Mass Heal',9,'Evo','1 action','60 ft','V, S','Instantaneous',['Cleric'],
 'Restore up to 700 HP divided among any creatures you can see within range. Also ends blinded, deafened, and diseased.'],
['Mass Polymorph',9,'Tra','1 action','120 ft','V, S, M','Concentration, 1 hr',['Bard','Sorcerer','Wizard'],
 'Transform up to 10 creatures within 30 ft of each other: WIS save or become a beast of CR ≤ 1. Reverts at 0 HP. Upcast: transform into any CR beast.'],
['Meteor Swarm',9,'Evo','1 action','1 mile','V, S','Instantaneous',['Sorcerer','Wizard'],
 'Four meteors strike four 40-ft-radius spheres. Each sphere: DEX save or 20d6 fire + 20d6 bludgeoning damage (half on save). The spheres can\'t overlap.'],
['Power Word Heal',9,'Evo','1 action','Touch','V, S','Instantaneous',['Bard'],
 'Restore all HP to one creature; end charmed, frightened, paralyzed, and stunned conditions; it can use its reaction to stand up.'],
['Power Word Kill',9,'Enc','1 action','60 ft','V','Instantaneous',['Bard','Sorcerer','Warlock','Wizard'],
 'If the target has 100 HP or fewer, it dies instantly. No save.'],
['Prismatic Wall',9,'Abj','1 action','60 ft','V, S','10 min',['Wizard'],
 '90-ft-long, 30-ft-high wall with 7 layers (one per color): each deals damage/conditions and requires a specific method to pass through. Dispelled one layer at a time.'],
['Shapechange',9,'Tra','1 action','Self','V, S, M (1500 gp jade circlet)','Concentration, 1 hr',['Druid','Wizard'],
 'Transform into any creature (not a construct or undead) whose CR is ≤ your level. Retain your mental ability scores. Change form as action.'],
['Storm of Vengeance',9,'Con','1 action','Sight','V, S','Concentration, 1 min',['Druid'],
 'Storm cloud over 360-ft radius. Each round a different effect: 1 thunder 2d6, 2 lightning 10d6 to 10 targets, 3 hail 2d6 cold, 4-10 acid/freezing rain 1d6 each.'],
['Time Stop',9,'Tra','1 action','Self','V','Instantaneous',['Sorcerer','Wizard'],
 'Take 1d4+1 extra turns in a row. Other creatures can\'t move or act. Spell ends early if you affect another creature or move something another creature is carrying.'],
['True Polymorph',9,'Tra','1 action','30 ft','V, S, M','Concentration, 1 hr',['Bard','Warlock','Wizard'],
 'Transform a creature into any creature/object, or an object into a creature. WIS save (unwilling). Concentration 1 hr; if held 1 hr, becomes permanent.'],
['True Resurrection',9,'Nec','1 hr','Touch','V, S, M (25000 gp gem dust)','Instantaneous',['Cleric','Druid'],
 'Restore life to a creature dead for up to 200 years in a new perfect body. Doesn\'t require the body. Overrides all but divine intervention.'],
['Weird',9,'Ill','1 action','120 ft','V, S','Concentration, 1 min',['Wizard'],
 '30-ft sphere: WIS save or frightened and 4d10 psychic damage at the start of each of your turns. Repeat save each turn. Ends on success.'],
['Wish',9,'Con','1 action','Self','V','Instantaneous',['Sorcerer','Wizard'],
 'Duplicate any spell of 8th level or lower, or create a reality-altering effect of your choice. Stress: STR drops to 3 for 2d4 days; 33% chance to never cast Wish again if used for a non-duplicate effect.']
];
