# Regenerates sw-assets.js - run whenever files are added/removed (docs/09).
# Usage: powershell -File tools/gen-sw-assets.ps1
$root = Split-Path -Parent $PSScriptRoot
$patterns = @('*.html', '*.css', '*.js', '*.webmanifest', '*.png', '*.svg')
$files = Get-ChildItem -Path $root -Recurse -File -Include $patterns |
  Where-Object {
    $_.FullName -notmatch '\\(\.git|\.claude|docs|tools)\\' -and
    $_.Name -ne 'sw.js' -and $_.Name -ne 'sw-assets.js'
  } |
  ForEach-Object { './' + ($_.FullName.Substring($root.Length + 1) -replace '\\', '/') } |
  Sort-Object
$list = ($files | ForEach-Object { "  '$_'" }) -join ",`n"
$content = "/* Generated by tools/gen-sw-assets.ps1 - do not edit by hand. */`nself.SW_ASSETS = [`n$list`n];`n"
Set-Content -Path (Join-Path $root 'sw-assets.js') -Value $content -Encoding Ascii
Write-Host "sw-assets.js written with $($files.Count) assets."
